# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Joshua DeMoss
#
# The `code_values` entry (docs/contributing/repository-conventions.md#values-the-code-owns): each
# value tests/code_values.txt registers is read from its owner; a marker that differs, an owner
# gone, an unmarked copy of a known value and a test count naming no commit and command are reds.
#   cmake [-DZEN_VALUES_WRITE=ON] -P tests/check_code_values.cmake   (from the root, or -DZEN_REPO=)
# ZEN_VALUES_WRITE=ON first rewrites every marker to its owner's value, and touches nothing else.

cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ZEN_REPO OR ZEN_REPO STREQUAL "")
    set(ZEN_REPO "${CMAKE_CURRENT_LIST_DIR}/..")
endif()
get_filename_component(ZEN_REPO "${ZEN_REPO}" ABSOLUTE)
if(NOT EXISTS "${ZEN_REPO}/AGENTS.md")
    message(FATAL_ERROR "code-values: '${ZEN_REPO}' is not this repository's root "
                        "(no AGENTS.md). Pass -DZEN_REPO=<repository root>.")
endif()

# ---- scope -----------------------------------------------------------------------------
# Every current-facing *.md, and the comments of every first-party C/C++ and CMake file. Frozen
# history, vendored and build trees are not current-facing; the registry is read, not held, and
# this file's examples are copies by design.
set(ZEN_VALUES_REGISTRY tests/code_values.txt)
set(ZEN_VALUES_EXCLUDE
    "^build(-[^/]*)?/" "^cmake-build" "^_install" "^out/" "^[.]git(/|$)" "^[.]idea/" "^[.]vscode/"
    "^[.]claude/" "^docs/history/" "^reference/" "third_party/"
    "^tests/check_code_values[.]cmake$")
set(ZEN_VALUES_SOURCE_GLOBS *.h *.hpp *.ipp *.inl *.c *.cc *.cpp *.cxx CMakeLists.txt *.cmake)

# The four characters a CMake list cannot hold, swapped for control characters no text carries;
# every comparison is made on swapped text, and the swap is undone only to print or to write.
string(ASCII 1 ZEN_SOH)
string(ASCII 2 ZEN_STX)
string(ASCII 3 ZEN_ETX)
string(ASCII 4 ZEN_EOT)
function(zen_values_swap text out)
    string(REPLACE "\r" "" text "${text}")
    string(REPLACE ";" "${ZEN_SOH}" text "${text}")
    string(REPLACE "[" "${ZEN_STX}" text "${text}")
    string(REPLACE "]" "${ZEN_ETX}" text "${text}")
    string(REPLACE "\\" "${ZEN_EOT}" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()
function(zen_values_show text out)
    string(REPLACE "${ZEN_SOH}" ";" text "${text}")
    string(REPLACE "${ZEN_STX}" "[" text "${text}")
    string(REPLACE "${ZEN_ETX}" "]" text "${text}")
    string(REPLACE "${ZEN_EOT}" "\\" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()
function(zen_values_escape text out)
    string(REGEX REPLACE "([+.*?^$|(){}])" "\\\\\\1" e "${text}")
    set(${out} "${e}" PARENT_SCOPE)
endfunction()

# ---- the owner: a declaration read from the code ---------------------------------------
# One declaration of ${symbol} in ${code} (comments already stripped): `#define S v`, `S = v;`,
# `S{v}`, `set(S v)`, or, for a quoted symbol, `"S", v` (a shape's name and version). Sets
# ${out_expr} to its value's text, or ${out_why} to why there is not exactly one.
function(zen_values_declaration code symbol out_expr out_why)
    set(${out_expr} "" PARENT_SCOPE)
    set(${out_why} "" PARENT_SCOPE)
    zen_values_escape("${symbol}" s)
    set(found "")
    if(symbol MATCHES "^\"")
        string(REGEX MATCHALL "${s}[ \t]*,[ \t]*[0-9]+" hits "${code}")
        foreach(h IN LISTS hits)
            string(REGEX REPLACE "^.*,[ \t]*" "" v "${h}")
            list(APPEND found "${v}")
        endforeach()
    elseif(ZEN_VALUES_OWNER_IS_PYTHON)
        # Python: `S = v` (or `S: T = v`) at the start of a line, a module's or a class's.
        string(REGEX MATCHALL "(^|\n)[ \t]*${s}[ \t]*(:[^=\n]*)?=[ \t]*[^\n#]+" hits "${code}")
        foreach(h IN LISTS hits)
            string(REGEX REPLACE "^[^=]*=[ \t]*" "" v "${h}")
            string(STRIP "${v}" v)
            list(APPEND found "${v}")
        endforeach()
    else()
        set(edge "(^|[^A-Za-z0-9_])")
        foreach(form
                "#[ \t]*define[ \t]+${s}[ \t]+([^\n]+)"
                "${edge}${s}[ \t]*=([^=\n][^${ZEN_SOH}\n]*)${ZEN_SOH}"
                "${edge}${s}[ \t]*\\{([^}\n]*)\\}"
                "set\\(${s}[ \t]+([^)\n]+)\\)")
            string(REGEX MATCHALL "${form}" hits "${code}")
            string(SUBSTRING "${form}" 0 1 form_head)
            foreach(h IN LISTS hits)
                string(REGEX MATCH "${form}" _ "${h}")
                # The groups are read before any other match: a MATCHES that misses resets them.
                set(g1 "${CMAKE_MATCH_1}")
                set(g2 "${CMAKE_MATCH_2}")
                if(form_head STREQUAL "#" OR form_head STREQUAL "s")
                    set(v "${g1}")
                else()
                    set(v "${g2}")
                endif()
                string(STRIP "${v}" v)
                list(APPEND found "${v}")
            endforeach()
        endforeach()
    endif()
    list(LENGTH found n)
    if(n EQUAL 0)
        set(${out_why} "declares no ${symbol}" PARENT_SCOPE)
    elseif(n GREATER 1)
        set(${out_why} "declares ${symbol} ${n} times" PARENT_SCOPE)
    else()
        set(${out_expr} "${found}" PARENT_SCOPE)
    endif()
endfunction()

# The integer an owner's value text spells: literals with their suffixes and separators, the
# standard integer types' braces and casts, arithmetic, and another constant of the same file
# (three levels deep). Sets ${out_value}, or ${out_why} to what this reading cannot evaluate.
function(zen_values_evaluate expr code depth out_value out_why)
    set(${out_value} "" PARENT_SCOPE)
    set(${out_why} "" PARENT_SCOPE)
    set(e "${expr}")
    string(REGEX REPLACE "std::[a-z0-9_]+[ \t]*\\{([^{}]*)\\}" "(\\1)" e "${e}")
    string(REGEX REPLACE "static_cast<[^<>]*>" "" e "${e}")
    string(REGEX REPLACE "([0-9])'([0-9])" "\\1\\2" e "${e}")
    string(REGEX REPLACE "([0-9a-fA-F])(ull|ULL|ul|UL|ll|LL|u|U|l|L|z|Z)([^A-Za-z0-9_]|$)" "\\1\\3" e "${e}")
    string(REGEX REPLACE "([A-Za-z_][A-Za-z0-9_]*::)+([A-Za-z_])" "\\2" e "${e}")
    if(ZEN_VALUES_OWNER_IS_PYTHON)
        string(REGEX REPLACE "([0-9])[.]0([^0-9]|$)" "\\1\\2" e "${e}")   # 30.0 is 30
        string(REPLACE "//" "/" e "${e}")
        string(REGEX MATCHALL "[A-Z][A-Z0-9_][A-Z0-9_]+" refs "${e}")
    else()
        string(REGEX MATCHALL "k[A-Z][A-Za-z0-9_]*" refs "${e}")
    endif()
    foreach(ref IN LISTS refs)
        if(depth GREATER 2)
            set(${out_why} "names ${ref} too deep to follow" PARENT_SCOPE)
            return()
        endif()
        zen_values_declaration("${code}" "${ref}" ref_expr ref_why)
        if(NOT ref_why STREQUAL "")
            # Another file's constant: the value a registered owner of that name gave.
            get_property(ref_value GLOBAL PROPERTY "zen_values_by_symbol_${ref}")
            if("${ref_value}" STREQUAL "")
                set(${out_why} "names ${ref}, which its file does not declare and no registered value holds" PARENT_SCOPE)
                return()
            endif()
        else()
            math(EXPR next "${depth} + 1")
            zen_values_evaluate("${ref_expr}" "${code}" ${next} ref_value ref_why)
            if(NOT ref_why STREQUAL "")
                set(${out_why} "${ref_why}" PARENT_SCOPE)
                return()
            endif()
        endif()
        string(REGEX REPLACE "(^|[^A-Za-z0-9_])${ref}([^A-Za-z0-9_]|$)" "\\1(${ref_value})\\2" e "${e}")
    endforeach()
    string(STRIP "${e}" e)
    if(NOT e MATCHES "^[-0-9a-fA-FxX +*/%()<>&|^~]+$" OR e MATCHES "[g-wyzG-WYZ]")
        zen_values_show("${expr}" shown)
        set(${out_why} "spells `${shown}`, which this check cannot evaluate" PARENT_SCOPE)
        return()
    endif()
    math(EXPR v "${e}")
    set(${out_value} "${v}" PARENT_SCOPE)
endfunction()

# ---- rendering a value, the only way a marker may spell it -----------------------------
# none: the integer; KiB, MiB, GiB: divided exactly; s: milliseconds as seconds, exactly; pow2:
# `2^N`; grouped: thousands separated by commas.
function(zen_values_render value format out_text out_why)
    set(${out_text} "" PARENT_SCOPE)
    set(${out_why} "" PARENT_SCOPE)
    set(divisor 1)
    if(format STREQUAL "KiB")
        set(divisor 1024)
    elseif(format STREQUAL "MiB")
        set(divisor 1048576)
    elseif(format STREQUAL "GiB")
        set(divisor 1073741824)
    elseif(format STREQUAL "s")
        set(divisor 1000)
    endif()
    if(format STREQUAL "pow2")
        set(p 0)
        set(x 1)
        while(x LESS value AND p LESS 62)
            math(EXPR x "${x} * 2")
            math(EXPR p "${p} + 1")
        endwhile()
        if(NOT x EQUAL value)
            set(${out_why} "${value} is no power of two" PARENT_SCOPE)
            return()
        endif()
        set(${out_text} "2^${p}" PARENT_SCOPE)
        return()
    endif()
    math(EXPR rest "${value} % ${divisor}")
    if(NOT rest EQUAL 0)
        set(${out_why} "${value} is not a whole number of ${format}" PARENT_SCOPE)
        return()
    endif()
    math(EXPR shown "${value} / ${divisor}")
    if(format STREQUAL "grouped")
        set(t "${shown}")
        set(shown "")
        while(t MATCHES "^(-?[0-9]+)([0-9][0-9][0-9])$")
            set(shown ",${CMAKE_MATCH_2}${shown}")
            set(t "${CMAKE_MATCH_1}")
        endwhile()
        set(shown "${t}${shown}")
    endif()
    set(${out_text} "${shown}" PARENT_SCOPE)
endfunction()

# A spelling from the registry or a marker as a regex over swapped text: `{}` is the value as an
# integer, `{KiB}` and the other formats as zen_values_render spells them; one group, the number.
function(zen_values_spelling_regex spelling out_regex out_format)
    set(format "")
    if(spelling MATCHES "\\{([A-Za-z0-9]*)\\}")
        set(format "${CMAKE_MATCH_1}")
    endif()
    string(REGEX REPLACE "\\{[A-Za-z0-9]*\\}" "@NUMBER@" s "${spelling}")
    zen_values_escape("${s}" s)
    string(REPLACE "@NUMBER@" "([0-9]+(,[0-9][0-9][0-9])*(\^[0-9]+)?)" s "${s}")
    set(${out_regex} "${s}" PARENT_SCOPE)
    set(${out_format} "${format}" PARENT_SCOPE)
endfunction()

# ---- the registry ----------------------------------------------------------------------
# `<id> <owner file> <symbol>` registers a value; `claim <id> <spelling>` and `mention <id>
# <spelling>` register how it is written without its owner's name. A claim states the current
# value, so every unmarked one is a copy; a mention at the current value is a copy unless it
# reads "since", "from" or "and later"; a mention below it is a statement about that version.
function(zen_values_parse_registry text out_ids)
    string(REPLACE "\n" ";" lines "${text}")
    set(ids "")
    set(n 0)
    foreach(line IN LISTS lines)
        math(EXPR n "${n} + 1")
        string(STRIP "${line}" line)
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        if(line MATCHES "^(claim|mention)[ \t]+([^ \t]+)[ \t]+(.+)$")
            set(kind "${CMAKE_MATCH_1}")
            set(id "${CMAKE_MATCH_2}")
            set(spelling "${CMAKE_MATCH_3}")
            if(NOT id IN_LIST ids)
                message(FATAL_ERROR "code-values: ${ZEN_VALUES_REGISTRY}:${n} spells ${id} before registering it")
            endif()
            if(NOT spelling MATCHES "\\{[A-Za-z0-9]*\\}")
                message(FATAL_ERROR "code-values: ${ZEN_VALUES_REGISTRY}:${n} has no `{}` for the number")
            endif()
            set_property(GLOBAL APPEND PROPERTY "zen_values_${kind}_${id}" "${spelling}")
        elseif(line MATCHES "^([A-Za-z_][A-Za-z0-9_:.]*)[ \t]+([^ \t]+)[ \t]+([^ \t]+)$")
            set(id "${CMAKE_MATCH_1}")
            if(id IN_LIST ids)
                message(FATAL_ERROR "code-values: ${ZEN_VALUES_REGISTRY}:${n} registers ${id} twice")
            endif()
            list(APPEND ids "${id}")
            set_property(GLOBAL PROPERTY "zen_values_owner_${id}" "${CMAKE_MATCH_2}")
            set_property(GLOBAL PROPERTY "zen_values_symbol_${id}" "${CMAKE_MATCH_3}")
        else()
            zen_values_show("${line}" shown)
            message(FATAL_ERROR "code-values: ${ZEN_VALUES_REGISTRY}:${n} is neither `<id> <owner> "
                                "<symbol>` nor `claim|mention <id> <spelling>`: ${shown}")
        endif()
    endforeach()
    set(${out_ids} "${ids}" PARENT_SCOPE)
endfunction()

# The name the text uses for a value: its id when the id is qualified (`setup::kFormatVersion`,
# since the bare name is another file's too, or `Connection.MAX_OPEN`), else its symbol; "" for a
# quoted symbol.
function(zen_values_text_name id out)
    get_property(symbol GLOBAL PROPERTY "zen_values_symbol_${id}")
    if(symbol MATCHES "^\"")
        set(${out} "" PARENT_SCOPE)
    elseif(id MATCHES "::|[.]")
        set(${out} "${id}" PARENT_SCOPE)
    else()
        set(${out} "${symbol}" PARENT_SCOPE)
    endif()
endfunction()

# ---- reading one text ------------------------------------------------------------------
# One document's markers, checked (and in write mode rewritten): a span marker's text is its value
# as its format renders it; a spelling marker holds its own line, or, alone, the next line or the
# fenced block that line opens, and what it holds carries the spelling, each time with the value
# (the standard the header names). Sets ${out_findings}, the lines held as ${out_held}
# (`<n>|<id>` each), and ${out_text} to the text, rewritten when asked.
function(zen_values_tally)
    get_property(k GLOBAL PROPERTY zen_values_checked)
    if("${k}" STREQUAL "")
        set(k 0)
    endif()
    math(EXPR k "${k} + 1")
    set_property(GLOBAL PROPERTY zen_values_checked "${k}")
endfunction()
function(zen_values_markers rel text write out_findings out_held out_text)
    string(REPLACE "\n" ";" lines "${text}")
    set(findings "")
    set(held "")
    set(rewritten "")
    set(pending "")      # lone spelling markers waiting for what they hold: `<n>|<id>|<spelling>`
    set(opened "")       # every spelling marker, `<n>|<id>|<spelling>`
    set(carried "")      # the markers whose lines carried their spelling
    set(in_fence 0)
    set(fence_held "")
    set(in_example 0)    # a fenced block no marker opened: what it shows is an example
    set(n 0)
    foreach(line IN LISTS lines)
        math(EXPR n "${n} + 1")
        set(scope_lines "")
        if(in_example OR (NOT in_fence AND pending STREQUAL "" AND line MATCHES "^[ \t]*```"))
            if(line MATCHES "^[ \t]*```")
                if(in_example)
                    set(in_example 0)
                else()
                    set(in_example 1)
                endif()
            endif()
            list(APPEND rewritten "${line}")
            continue()
        endif()
        # A line of lone spelling markers holds nothing itself: stacked, they all wait for what
        # follows them.
        string(REGEX MATCHALL "<!-- value [^ >]+ in \"[^\"]*\" -->" spells "${line}")
        string(REGEX REPLACE "<!-- value [^ >]+ in \"[^\"]*\" -->" "" rest "${line}")
        string(STRIP "${rest}" rest)
        set(marker_only 0)
        if(spells AND rest STREQUAL "")
            set(marker_only 1)
        endif()
        # A fenced block a lone marker opened is held to its closing fence.
        if(in_fence)
            if(line MATCHES "^[ \t]*```")
                set(in_fence 0)
                set(fence_held "")
            else()
                set(scope_lines "${fence_held}")
            endif()
        elseif(NOT pending STREQUAL "" AND NOT marker_only AND NOT line MATCHES "^[ \t]*$")
            set(scope_lines "${pending}")
            if(line MATCHES "^[ \t]*```")
                set(in_fence 1)
                set(fence_held "${pending}")
                set(scope_lines "")
            endif()
            set(pending "")
        endif()
        # Span markers.
        set(out_line "${line}")
        string(REGEX MATCHALL "<!-- value [^ >]+( [A-Za-z0-9]+)? -->[^<]*<!-- /value -->" spans "${line}")
        foreach(span IN LISTS spans)
            zen_values_tally()
            string(REGEX MATCH "^<!-- value ([^ >]+)( ([A-Za-z0-9]+))? -->([^<]*)<!-- /value -->$" _ "${span}")
            set(id "${CMAKE_MATCH_1}")
            set(format_part "${CMAKE_MATCH_2}")
            set(format "${CMAKE_MATCH_3}")
            set(shown_text "${CMAKE_MATCH_4}")
            # Several ids, comma-separated, are one value two owners share: all must agree.
            string(REPLACE "," ";" span_ids "${id}")
            set(want "")
            set(bad 0)
            foreach(span_id IN LISTS span_ids)
                get_property(value GLOBAL PROPERTY "zen_values_value_${span_id}")
                if("${value}" STREQUAL "")
                    list(APPEND findings "${rel}:${n}: a marker names `${span_id}`, which ${ZEN_VALUES_REGISTRY} does not register (or whose owner could not be read)")
                    set(bad 1)
                    break()
                endif()
                zen_values_render("${value}" "${format}" one why)
                if(NOT why STREQUAL "")
                    list(APPEND findings "${rel}:${n}: `${span_id}` cannot be shown as ${format}: ${why}")
                    set(bad 1)
                    break()
                endif()
                if(want STREQUAL "")
                    set(want "${one}")
                elseif(NOT one STREQUAL want)
                    list(APPEND findings "${rel}:${n}: the marker's owners disagree: `${span_ids}` say ${want} and ${one}")
                    set(bad 1)
                    break()
                endif()
            endforeach()
            if(bad)
                continue()
            endif()
            if(NOT shown_text STREQUAL want)
                if(write)
                    string(REPLACE "${span}" "<!-- value ${id}${format_part} -->${want}<!-- /value -->" out_line "${out_line}")
                else()
                    list(GET span_ids 0 first_id)
                    get_property(owner GLOBAL PROPERTY "zen_values_owner_${first_id}")
                    list(APPEND findings "${rel}:${n}: says ${shown_text} for `${id}`, and ${owner} says ${want} -- run with -DZEN_VALUES_WRITE=ON to rewrite the marker")
                endif()
            endif()
        endforeach()
        # Spelling markers: this line's own, or a lone one for what follows.
        foreach(spell IN LISTS spells)
            string(REGEX MATCH "^<!-- value ([^ >]+) in \"([^\"]*)\" -->$" _ "${spell}")
            set(entry "${n}|${CMAKE_MATCH_1}|${CMAKE_MATCH_2}")
            list(APPEND opened "${entry}")
            zen_values_tally()
            if(rest STREQUAL "")
                list(APPEND pending "${entry}")
            else()
                list(APPEND scope_lines "${entry}")
            endif()
        endforeach()
        foreach(entry IN LISTS scope_lines)
            string(REGEX MATCH "^[0-9]+[|]([^|]*)[|](.*)$" _ "${entry}")
            set(id "${CMAKE_MATCH_1}")
            set(spelling "${CMAKE_MATCH_2}")
            list(APPEND held "${n}|${id}")
            get_property(value GLOBAL PROPERTY "zen_values_value_${id}")
            if("${value}" STREQUAL "")
                continue()       # said once, where the marker stands (below)
            endif()
            zen_values_spelling_regex("${spelling}" rx format)
            zen_values_render("${value}" "${format}" want why)
            string(REGEX MATCHALL "${rx}" hits "${out_line}")
            if(hits)
                list(APPEND carried "${entry}")
            endif()
            foreach(hit IN LISTS hits)
                string(REGEX MATCH "${rx}" _ "${hit}")
                if(NOT CMAKE_MATCH_1 STREQUAL want)
                    if(write)
                        string(REPLACE "${CMAKE_MATCH_1}" "${want}" fixed "${hit}")
                        string(REPLACE "${hit}" "${fixed}" out_line "${out_line}")
                    else()
                        get_property(owner GLOBAL PROPERTY "zen_values_owner_${id}")
                        list(APPEND findings "${rel}:${n}: says ${CMAKE_MATCH_1} in \"${spelling}\" for `${id}`, and ${owner} says ${want} -- run with -DZEN_VALUES_WRITE=ON to rewrite it")
                    endif()
                endif()
            endforeach()
        endforeach()
        list(APPEND rewritten "${out_line}")
    endforeach()
    foreach(entry IN LISTS opened)
        string(REGEX MATCH "^([0-9]+)[|]([^|]*)[|](.*)$" _ "${entry}")
        get_property(value GLOBAL PROPERTY "zen_values_value_${CMAKE_MATCH_2}")
        if("${value}" STREQUAL "")
            list(APPEND findings "${rel}:${CMAKE_MATCH_1}: a marker names `${CMAKE_MATCH_2}`, which ${ZEN_VALUES_REGISTRY} does not register (or whose owner could not be read)")
        elseif(NOT entry IN_LIST carried)
            list(APPEND findings "${rel}:${CMAKE_MATCH_1}: a value marker for `${CMAKE_MATCH_2}` holds no line carrying \"${CMAKE_MATCH_3}\"")
        endif()
    endforeach()
    string(REPLACE ";" "\n" out "${rewritten}")
    set(${out_findings} "${findings}" PARENT_SCOPE)
    set(${out_held} "${held}" PARENT_SCOPE)
    set(${out_text} "${out}" PARENT_SCOPE)
endfunction()

# The unmarked copies on one current-facing line (a document's line, or a comment's text), its
# markers already taken out: the owner's name with a number right beside it (`kMax` | 64,
# `kMax` (64), `kMax` = 64), a registered claim, and a registered mention at the current value
# not read as "since". Arithmetic on the name (`kMax + 1`) is no copy. ${held} lists the ids a
# spelling marker holds on this line. Sets ${out} to the findings.
function(zen_values_unmarked where line ids held out)
    set(found "")
    foreach(id IN LISTS ids)
        get_property(value GLOBAL PROPERTY "zen_values_value_${id}")
        if("${value}" STREQUAL "" OR id IN_LIST held)
            continue()           # a spelling marker holds this line for the value
        endif()
        zen_values_text_name("${id}" name)
        if(NOT name STREQUAL "")
            string(FIND "${line}" "${name}" at)
            set(rest "${line}")
            while(NOT at EQUAL -1)
                set(before "")
                if(at GREATER 0)
                    math(EXPR b "${at} - 1")
                    string(SUBSTRING "${rest}" ${b} 1 before)
                endif()
                string(LENGTH "${name}" len)
                math(EXPR after_at "${at} + ${len}")
                string(SUBSTRING "${rest}" ${after_at} -1 rest)
                if(NOT before MATCHES "[A-Za-z0-9_]" AND NOT rest MATCHES "^[A-Za-z0-9_]"
                   AND rest MATCHES "^`?[ \t]*([|=(:,]|is |of )?[ \t]*([*][*])?[~]?[0-9]")
                    zen_values_show("${line}" shown)
                    string(STRIP "${shown}" shown)
                    list(APPEND found "${where}: an unmarked copy of `${id}` -- name the owner alone, or mark the number (<!-- value ${id} -->...<!-- /value -->): ${shown}")
                    break()
                endif()
                string(FIND "${rest}" "${name}" at)
            endwhile()
        endif()
        foreach(kind claim mention)
            get_property(spellings GLOBAL PROPERTY "zen_values_${kind}_${id}")
            foreach(spelling IN LISTS spellings)
                zen_values_spelling_regex("${spelling}" rx format)
                zen_values_render("${value}" "${format}" want why)
                string(REGEX MATCHALL "${rx}" hits "${line}")
                foreach(hit IN LISTS hits)
                    string(REGEX MATCH "${rx}" _ "${hit}")
                    set(number "${CMAKE_MATCH_1}")
                    if(kind STREQUAL "mention")
                        string(FIND "${line}" "${hit}" hit_at)
                        string(SUBSTRING "${line}" 0 ${hit_at} lead)
                        string(TOLOWER "${lead}" lead)
                        string(LENGTH "${hit}" hit_len)
                        math(EXPR tail_at "${hit_at} + ${hit_len}")
                        string(SUBSTRING "${line}" ${tail_at} -1 tail)
                        string(TOLOWER "${tail}" tail)
                        # A statement about that version, which stays true when the value moves.
                        if(lead MATCHES "(since|from|at least|before|after|until|as of)[ \t]+[^ \t]*$"
                           OR tail MATCHES "^[` \t]*((and|or) (later|newer|above)|adds|added|introduces|introduced)")
                            continue()
                        endif()
                        if(NOT number MATCHES "^[0-9]+$" OR NOT want MATCHES "^[0-9]+$")
                            continue()
                        endif()
                        if(number LESS want)
                            continue()
                        endif()
                    endif()
                    zen_values_show("${line}" shown)
                    string(STRIP "${shown}" shown)
                    list(APPEND found "${where}: an unmarked ${kind} of `${id}` (\"${spelling}\") -- mark it, or say it by the owner's name: ${shown}")
                endforeach()
            endforeach()
        endforeach()
    endforeach()
    set(${out} "${found}" PARENT_SCOPE)
endfunction()

# A test count: `27/27`, `30 of 30 passed`, `PASSED 30`, or a count of cases, assertions, entries,
# suites or mutations beside a verdict. Outside the population files it names the commit and
# the command that measured it, in its own paragraph. Sets ${out} to the count found, or "".
function(zen_values_count line out)
    set(${out} "" PARENT_SCOPE)
    string(TOLOWER "${line}" low)
    # N/N, the same number twice, is a whole population reported green; 50/50 is an even split.
    string(REGEX MATCHALL "(^|[^0-9/.])[0-9]+/[0-9]+([^0-9/.]|$)" pairs "${low}")
    foreach(pair IN LISTS pairs)
        string(REGEX MATCH "([0-9]+)/([0-9]+)" _ "${pair}")
        if(CMAKE_MATCH_1 STREQUAL CMAKE_MATCH_2 AND CMAKE_MATCH_1 GREATER 1 AND NOT CMAKE_MATCH_1 EQUAL 50)
            set(${out} "${CMAKE_MATCH_0}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    foreach(pattern
            "(^|[^0-9])[0-9]+ of [0-9]+ (pass|green|ran|test|case|entr|suite)"
            "passed [0-9]+ of [0-9]+"
            "(^|[^0-9])[0-9][0-9,]* (test cases|cases|assertions|ctest entries|mutations)[^.]*(pass|green|red|caught|ran)")
        if(low MATCHES "${pattern}")
            string(REGEX REPLACE "^[^0-9a-z]+" "" found "${CMAKE_MATCH_0}")
            set(${out} "${found}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
endfunction()
function(zen_values_attributed paragraph out)
    if(paragraph MATCHES "`[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]+`"
       AND paragraph MATCHES "`(cmake|ctest|python|bash|\\./)[^`]*`")
        set(${out} 1 PARENT_SCOPE)
    else()
        set(${out} 0 PARENT_SCOPE)
    endif()
endfunction()

# The comment text of a C/C++ or CMake file, as `<line>|<text>` entries: `//` to the line's end and
# every line of a `/* */` block (C/C++), `#` to the line's end (CMake). A `//` in a string literal
# is read as a comment: this reading sees more comment, never less.
function(zen_values_comments rel content out)
    set(entries "")
    string(REPLACE "\n" ";" lines "${content}")
    set(n 0)
    set(in_block 0)
    set(cmake 0)
    if(rel MATCHES "(CMakeLists[.]txt|[.]cmake)$")
        set(cmake 1)
    endif()
    foreach(line IN LISTS lines)
        math(EXPR n "${n} + 1")
        if(cmake)
            if(line MATCHES "^[ \t]*#(.*)$")
                list(APPEND entries "${n}|${CMAKE_MATCH_1}")
            endif()
            continue()
        endif()
        set(text "")
        if(in_block)
            string(FIND "${line}" "*/" close)
            if(close EQUAL -1)
                list(APPEND entries "${n}|${line}")
                continue()
            endif()
            string(SUBSTRING "${line}" 0 ${close} text)
            math(EXPR close "${close} + 2")
            string(SUBSTRING "${line}" ${close} -1 line)
            set(in_block 0)
        endif()
        string(FIND "${line}" "//" slash)
        string(FIND "${line}" "/*" open)
        if(NOT slash EQUAL -1 AND (open EQUAL -1 OR slash LESS open))
            math(EXPR slash "${slash} + 2")
            string(SUBSTRING "${line}" ${slash} -1 tail)
            string(APPEND text " ${tail}")
        elseif(NOT open EQUAL -1)
            math(EXPR open "${open} + 2")
            string(SUBSTRING "${line}" ${open} -1 tail)
            string(FIND "${tail}" "*/" close)
            if(close EQUAL -1)
                set(in_block 1)
                string(APPEND text " ${tail}")
            else()
                string(SUBSTRING "${tail}" 0 ${close} inner)
                string(APPEND text " ${inner}")
            endif()
        endif()
        string(STRIP "${text}" text)
        if(NOT text STREQUAL "")
            list(APPEND entries "${n}|${text}")
        endif()
    endforeach()
    set(${out} "${entries}" PARENT_SCOPE)
endfunction()

# ---- the self-test: make it say NO, and make it say YES --------------------------------

zen_values_swap("constexpr std::size_t kA = 64 * 1024;\ninline constexpr int kB{400};\n#define ZEN_X 9u\nstatic_assert(kA == 65536);\nconstexpr auto kC = std::size_t{kB} * 2;\nconst auto s = SchemaBuilder(\"zen.Thing\", 5)\nset(ZEN_Y 20480)\n" st_code)
set(st_want "kA=65536" "kB=400" "ZEN_X=9" "kC=800" "\"zen.Thing\"=5" "ZEN_Y=20480")
foreach(pair IN LISTS st_want)
    string(REGEX MATCH "^(.*)=([0-9]+)$" _ "${pair}")
    set(sym "${CMAKE_MATCH_1}")
    set(want "${CMAKE_MATCH_2}")
    zen_values_declaration("${st_code}" "${sym}" expr why)
    if(why STREQUAL "")
        zen_values_evaluate("${expr}" "${st_code}" 0 got why)
    endif()
    if(NOT why STREQUAL "" OR NOT got STREQUAL want)
        message(FATAL_ERROR "code-values: SELF-TEST FAILED -- ${sym} read as '${got}' (${why}), want ${want}; an owner's value would then be misread")
    endif()
endforeach()
set(ZEN_VALUES_OWNER_IS_PYTHON ON)
zen_values_swap("MAX_FRAME = 64 * 1024 * 1024\nclass C:\n    MAX_POLL_READS = MAX_FRAME // (1 << 16) + 2\nWRITE_SECONDS = 30.0\n" st_py)
foreach(pair "MAX_POLL_READS=1026" "WRITE_SECONDS=30")
    string(REGEX MATCH "^(.*)=([0-9]+)$" _ "${pair}")
    set(sym "${CMAKE_MATCH_1}")
    set(want "${CMAKE_MATCH_2}")
    zen_values_declaration("${st_py}" "${sym}" expr why)
    if(why STREQUAL "")
        zen_values_evaluate("${expr}" "${st_py}" 0 got why)
    endif()
    if(NOT why STREQUAL "" OR NOT got STREQUAL want)
        message(FATAL_ERROR "code-values: SELF-TEST FAILED -- the Python ${sym} read as '${got}' (${why}), want ${want}")
    endif()
endforeach()
set(ZEN_VALUES_OWNER_IS_PYTHON OFF)
zen_values_declaration("${st_code}" "kMissing" expr st_missing_why)
zen_values_swap("constexpr int kD = 1;\nconstexpr int kD = 2;\n" st_twice)
zen_values_declaration("${st_twice}" "kD" expr st_twice_why)
if(st_missing_why STREQUAL "" OR NOT st_twice_why MATCHES "2 times")
    message(FATAL_ERROR "code-values: SELF-TEST FAILED -- a missing owner said '${st_missing_why}' and a doubled one '${st_twice_why}'; a value whose owner moved would then pass")
endif()
foreach(case "65536|KiB|64" "67108864|MiB|64" "2000|s|2" "1048576|pow2|2^20" "65536|grouped|65,536" "9||9")
    string(REPLACE "|" ";" parts "${case}")
    list(GET parts 0 v)
    list(GET parts 1 f)
    list(GET parts 2 want)
    zen_values_render("${v}" "${f}" got why)
    if(NOT got STREQUAL want)
        message(FATAL_ERROR "code-values: SELF-TEST FAILED -- ${v} rendered as ${f} gave '${got}' (${why}), want ${want}")
    endif()
endforeach()
zen_values_render(1000 KiB got st_inexact)
if(st_inexact STREQUAL "")
    message(FATAL_ERROR "code-values: SELF-TEST FAILED -- 1000 bytes rendered as KiB without complaint")
endif()

# Markers and copies over a synthetic registry and document: a true marker passes, a stale one is
# refused and rewritten, a spelling marker holds its fenced block, an unmarked copy by name and an
# unmarked claim are refused, arithmetic, a since-form and an earlier mention pass.
set_property(GLOBAL PROPERTY zen_values_value_kSelfA 64)
set_property(GLOBAL PROPERTY zen_values_owner_kSelfA "self/a.hpp")
set_property(GLOBAL PROPERTY zen_values_symbol_kSelfA kSelfA)
set_property(GLOBAL PROPERTY zen_values_value_SELF_ABI 9)
set_property(GLOBAL PROPERTY zen_values_owner_SELF_ABI "self/abi.h")
set_property(GLOBAL PROPERTY zen_values_symbol_SELF_ABI SELF_ABI)
set_property(GLOBAL PROPERTY zen_values_claim_SELF_ABI "(version **{}**)")
set_property(GLOBAL PROPERTY zen_values_mention_SELF_ABI "ABI v{}")
set(st_ids kSelfA SELF_ABI)
zen_values_swap("| `kSelfA` | <!-- value kSelfA -->64<!-- /value --> |\nold: <!-- value kSelfA -->32<!-- /value -->\n<!-- value SELF_ABI in \"weave ABI v{}\" -->\n\n```text\nhost 0.1, weave ABI v8, ok\n```\n" st_doc)
zen_values_markers("self.md" "${st_doc}" 0 st_findings st_held st_same)
zen_values_markers("self.md" "${st_doc}" 1 st_write_findings st_write_held st_written)
list(LENGTH st_findings st_nfind)
if(NOT st_nfind EQUAL 2 OR NOT st_findings MATCHES "self.md:2: says 32" OR NOT st_findings MATCHES "self.md:6: says 8"
   OR NOT st_written MATCHES "value kSelfA -->64<!-- /value -->\n" OR NOT st_written MATCHES "weave ABI v9, ok"
   OR NOT st_held MATCHES "6[|]SELF_ABI" OR NOT st_write_findings STREQUAL "")
    zen_values_show("${st_findings}" a)
    zen_values_show("${st_written}" b)
    message(FATAL_ERROR "code-values: SELF-TEST FAILED -- the markers said '${a}' (want a stale span on 2 and a stale spelling on 6), and write mode gave:\n${b}")
endif()
zen_values_swap("<!-- value kSelfA in \"a {} b\" -->\n<!-- value SELF_ABI in \"weave ABI v{}\" -->\n```text\na 64 b\nweave ABI v9\n```\n" st_stacked)
zen_values_swap("```markdown\n| `kSelfA` | <!-- value kSelfA -->32<!-- /value --> |\n<!-- value kSelfA in \"a {} b\" -->\n```\ntext after\n" st_example)
zen_values_markers("example.md" "${st_example}" 0 st_example_findings st_example_held st_example_same)
if(NOT st_example_findings STREQUAL "" OR NOT st_example_held STREQUAL "")
    zen_values_show("${st_example_findings}" a)
    message(FATAL_ERROR "code-values: SELF-TEST FAILED -- markers shown inside a fenced example were read as markers: '${a}'")
endif()
zen_values_markers("stacked.md" "${st_stacked}" 0 st_stacked_findings st_stacked_held st_stacked_same)
if(NOT st_stacked_findings STREQUAL "" OR NOT st_stacked_held MATCHES "4[|]kSelfA" OR NOT st_stacked_held MATCHES "5[|]SELF_ABI")
    zen_values_show("${st_stacked_findings}" a)
    message(FATAL_ERROR "code-values: SELF-TEST FAILED -- two stacked markers over one fenced block said '${a}' and held '${st_stacked_held}'")
endif()
set(st_bad 0)
foreach(case
        "1|`kSelfA` | 64 | the bound"
        "1|at most kSelfA (64) entries"
        "1|a C ABI (version **9**)"
        "1|ABI v9 carries it"
        "1|names ABI v10"
        "0|`kSelfA + 1` is the first refused"
        "0|since ABI v9 a weave declares"
        "0|ABI v7 returns the ticket"
        "0|ABI v9 adds the emits list"
        "0|the bound is `kSelfA`, and it is refused out loud"
        "0|kSelfAB 64")
    string(REGEX MATCH "^([01])[|](.*)$" _ "${case}")
    set(want "${CMAKE_MATCH_1}")
    zen_values_swap("${CMAKE_MATCH_2}" st_line)
    zen_values_unmarked("self" "${st_line}" "${st_ids}" "" st_found)
    list(LENGTH st_found got)
    if(NOT got EQUAL want)
        message(FATAL_ERROR "code-values: SELF-TEST FAILED -- '${CMAKE_MATCH_2}' gave ${got} unmarked copies, want ${want}")
    endif()
endforeach()
foreach(case
        "1|(measured 56.2 s -> 9.4 s at `-j24`, 27/27)"
        "1|the lane PASSED 30 of 30, gates active: always"
        "1|30 cases and 24 caught mutations were green"
        "0|a subscription names 1 to 8 shapes"
        "0|the newest 256 entries of every kind"
        "0|3/4 of the room"
        "0|a fixed 50/50 split is a consequence")
    string(REGEX MATCH "^([01])[|](.*)$" _ "${case}")
    zen_values_count("${CMAKE_MATCH_2}" st_count)
    if((CMAKE_MATCH_1 AND st_count STREQUAL "") OR (NOT CMAKE_MATCH_1 AND NOT st_count STREQUAL ""))
        message(FATAL_ERROR "code-values: SELF-TEST FAILED -- '${CMAKE_MATCH_2}' read as the count '${st_count}'")
    endif()
endforeach()
zen_values_attributed("30 of 30 at `8ceee9d`, `cmake -DZEN_BUILD_DIR=b -P tests/verify.cmake`" st_yes)
zen_values_attributed("30 of 30 at `8ceee9d`" st_no)
if(NOT st_yes OR st_no)
    message(FATAL_ERROR "code-values: SELF-TEST FAILED -- a count's attribution read ${st_yes} with a commit and command, ${st_no} with a commit alone")
endif()
foreach(p owner symbol value claim mention)
    foreach(id kSelfA SELF_ABI)
        set_property(GLOBAL PROPERTY "zen_values_${p}_${id}")
    endforeach()
endforeach()
set_property(GLOBAL PROPERTY zen_values_checked 0)

# ---- the registry, read from its owners ------------------------------------------------

if(NOT EXISTS "${ZEN_REPO}/${ZEN_VALUES_REGISTRY}")
    message(FATAL_ERROR "code-values: ${ZEN_VALUES_REGISTRY} does not exist; an empty registry is a red, not a pass")
endif()
file(READ "${ZEN_REPO}/${ZEN_VALUES_REGISTRY}" registry_text)
zen_values_swap("${registry_text}" registry_text)
zen_values_parse_registry("${registry_text}" ids)
list(LENGTH ids id_count)
if(id_count EQUAL 0)
    message(FATAL_ERROR "code-values: ${ZEN_VALUES_REGISTRY} registers nothing; an empty registry is a red, not a pass")
endif()
set(problems "")
# In passes, so a value defined from another file's registered constant waits for it; what is
# still unread after the last pass is a finding.
set(unread "${ids}")
foreach(pass 1 2 3 4)
set(unread_after "")
foreach(id IN LISTS unread)
    get_property(owner GLOBAL PROPERTY "zen_values_owner_${id}")
    get_property(symbol GLOBAL PROPERTY "zen_values_symbol_${id}")
    if(NOT EXISTS "${ZEN_REPO}/${owner}")
        if(pass EQUAL 1)
            list(APPEND problems "${ZEN_VALUES_REGISTRY}: `${id}`'s owner ${owner} does not exist")
        endif()
        continue()
    endif()
    file(READ "${ZEN_REPO}/${owner}" code)
    zen_values_swap("${code}" code)
    # Each owner's comments go by its own language's rule: a CMake file's `/*` is text, not a
    # comment, and reading it as one would swallow the file.
    set(ZEN_VALUES_OWNER_IS_PYTHON OFF)
    if(owner MATCHES "[.]py$")
        set(ZEN_VALUES_OWNER_IS_PYTHON ON)
        string(REGEX REPLACE "#[^\n]*" "" code "${code}")
    elseif(owner MATCHES "[.]cmake$|CMakeLists[.]txt$")
        string(REGEX REPLACE "(^|\n)[ \t]*#[^\n]*" "\\1" code "${code}")
    else()
        string(REGEX REPLACE "/[*]([^*]|[*]+[^*/])*[*]+/" "" code "${code}")
        string(REGEX REPLACE "//[^\n]*" "" code "${code}")
    endif()
    zen_values_declaration("${code}" "${symbol}" expr why)
    if(why STREQUAL "")
        zen_values_evaluate("${expr}" "${code}" 0 value why)
    endif()
    if(NOT why STREQUAL "")
        list(APPEND unread_after "${id}")
        if(pass EQUAL 4)
            list(APPEND problems "${ZEN_VALUES_REGISTRY}: `${id}`: ${owner} ${why}")
        endif()
        continue()
    endif()
    set_property(GLOBAL PROPERTY "zen_values_value_${id}" "${value}")
    set_property(GLOBAL PROPERTY "zen_values_by_symbol_${symbol}" "${value}")
endforeach()
set(unread "${unread_after}")
endforeach()

# ---- the population: every current-facing document and comment -------------------------

set(documents "")
set(sources "")
file(GLOB top RELATIVE "${ZEN_REPO}" "${ZEN_REPO}/*")
foreach(entry IN LISTS top)
    set(skip 0)
    foreach(rx IN LISTS ZEN_VALUES_EXCLUDE)
        if(entry MATCHES "${rx}" OR "${entry}/" MATCHES "${rx}")
            set(skip 1)
        endif()
    endforeach()
    if(skip)
        continue()
    endif()
    if(IS_DIRECTORY "${ZEN_REPO}/${entry}")
        file(GLOB_RECURSE found RELATIVE "${ZEN_REPO}" "${ZEN_REPO}/${entry}/*")
    else()
        set(found "${entry}")
    endif()
    foreach(rel IN LISTS found)
        set(skip 0)
        foreach(rx IN LISTS ZEN_VALUES_EXCLUDE)
            if(rel MATCHES "${rx}")
                set(skip 1)
            endif()
        endforeach()
        if(skip)
            continue()
        endif()
        get_filename_component(name "${rel}" NAME)
        if(name MATCHES "[.]md$")
            list(APPEND documents "${rel}")
            continue()
        endif()
        foreach(glob IN LISTS ZEN_VALUES_SOURCE_GLOBS)
            string(REPLACE "." "[.]" g "${glob}")
            string(REPLACE "*" ".*" g "${g}")
            if(name MATCHES "^${g}$")
                list(APPEND sources "${rel}")
                break()
            endif()
        endforeach()
    endforeach()
endforeach()
list(SORT documents)
list(SORT sources)
list(LENGTH documents document_count)
list(LENGTH sources source_count)
if(document_count EQUAL 0 OR source_count EQUAL 0)
    message(FATAL_ERROR "code-values: ${document_count} documents and ${source_count} sources found under "
                        "${ZEN_REPO}; an empty population is a red, not a pass")
endif()

# The words that bring a value into a text: its name, and each registered spelling's fixed part.
# A file holding none of them is not read line by line for that value.
foreach(id IN LISTS ids)
    set(terms "")
    zen_values_text_name("${id}" name)
    if(NOT name STREQUAL "")
        list(APPEND terms "${name}")
    endif()
    foreach(kind claim mention)
        get_property(spellings GLOBAL PROPERTY "zen_values_${kind}_${id}")
        foreach(spelling IN LISTS spellings)
            string(REGEX REPLACE "\\{[A-Za-z0-9]*\\}.*$" "" head "${spelling}")
            string(STRIP "${head}" head)
            if(head STREQUAL "")
                string(REGEX REPLACE "^.*\\{[A-Za-z0-9]*\\}" "" head "${spelling}")
                string(STRIP "${head}" head)
            endif()
            list(APPEND terms "${head}")
        endforeach()
    endforeach()
    set_property(GLOBAL PROPERTY "zen_values_terms_${id}" "${terms}")
endforeach()
# What may be a test count, cheaply: a digit beside a word a count is reported with.
set(ZEN_VALUES_COUNT_HINT "[0-9]/[0-9]|[0-9] of [0-9]|PASSED [0-9]|[0-9] (test cases|cases|assertions|CTest entries|mutations)")

set(marker_count 0)
set(copy_count 0)
set(count_count 0)
set(written_files "")
foreach(rel IN LISTS documents sources)
    file(READ "${ZEN_REPO}/${rel}" raw)
    zen_values_swap("${raw}" text)
    set(is_doc 0)
    if(rel MATCHES "[.]md$")
        set(is_doc 1)
    endif()
    set(held "")
    if(is_doc)
        string(FIND "${text}" "<!-- value " any_marker)
        if(NOT any_marker EQUAL -1)
            zen_values_markers("${rel}" "${text}" "${ZEN_VALUES_WRITE}" found held new_text)
            list(APPEND problems ${found})
            get_property(k GLOBAL PROPERTY zen_values_checked)
            set(marker_count "${k}")
            if(ZEN_VALUES_WRITE AND NOT new_text STREQUAL text)
                zen_values_show("${new_text}" out)
                file(WRITE "${ZEN_REPO}/${rel}" "${out}")
                list(APPEND written_files "${rel}")
                set(text "${new_text}")
            endif()
        endif()
    endif()
    # The values this file brings in, and whether it may report a count.
    set(file_ids "")
    set(file_terms "")
    foreach(id IN LISTS ids)
        get_property(terms GLOBAL PROPERTY "zen_values_terms_${id}")
        foreach(term IN LISTS terms)
            string(FIND "${text}" "${term}" at)
            if(NOT at EQUAL -1)
                list(APPEND file_ids "${id}")
                list(APPEND file_terms ${terms})
                break()
            endif()
        endforeach()
    endforeach()
    set(may_count 0)
    if(text MATCHES "${ZEN_VALUES_COUNT_HINT}")
        set(may_count 1)
    endif()
    if(NOT file_ids AND NOT may_count)
        continue()
    endif()
    if(is_doc)
        string(REPLACE "\n" ";" doc_lines "${text}")
        set(entries "")
        set(n 0)
        foreach(l IN LISTS doc_lines)
            math(EXPR n "${n} + 1")
            list(APPEND entries "${n}|${l}")
        endforeach()
    else()
        zen_values_comments("${rel}" "${text}" entries)
    endif()
    set(paragraph "")
    set(paragraph_counts "")
    set(last 0)
    foreach(entry IN LISTS entries ITEMS "@END@")
        if(entry STREQUAL "@END@")
            set(n -1)
            set(l "")
        else()
            string(REGEX MATCH "^([0-9]+)[|](.*)$" _ "${entry}")
            set(n "${CMAKE_MATCH_1}")
            set(l "${CMAKE_MATCH_2}")
        endif()
        # A paragraph ends at a blank line or, in a source, where the comment lines stop; its
        # counts are judged with the whole paragraph.
        string(STRIP "${l}" stripped)
        math(EXPR gap "${n} - ${last}")
        if(stripped STREQUAL "" OR n EQUAL -1 OR (NOT is_doc AND gap GREATER 1))
            if(NOT paragraph_counts STREQUAL "")
                zen_values_attributed("${paragraph}" ok)
                if(NOT ok)
                    list(APPEND problems ${paragraph_counts})
                    list(LENGTH paragraph_counts k)
                    math(EXPR count_count "${count_count} + ${k}")
                endif()
            endif()
            set(paragraph "")
            set(paragraph_counts "")
            if(stripped STREQUAL "" OR n EQUAL -1)
                set(last "${n}")
                continue()
            endif()
        endif()
        set(last "${n}")
        string(APPEND paragraph " ${l}")
        set(near 0)
        foreach(term IN LISTS file_terms)
            string(FIND "${l}" "${term}" at)
            if(NOT at EQUAL -1)
                set(near 1)
                break()
            endif()
        endforeach()
        if(near OR (may_count AND l MATCHES "${ZEN_VALUES_COUNT_HINT}"))
            string(REGEX REPLACE "<!-- value [^>]*-->[^<]*<!-- /value -->" "@" bare "${l}")
            string(REGEX REPLACE "<!-- value [^>]* in \"[^\"]*\" -->" "" bare "${bare}")
        endif()
        if(near)
            set(line_held "")
            foreach(h IN LISTS held)
                if(h MATCHES "^${n}[|](.*)$")
                    list(APPEND line_held "${CMAKE_MATCH_1}")
                endif()
            endforeach()
            zen_values_unmarked("${rel}:${n}" "${bare}" "${file_ids}" "${line_held}" found)
            list(LENGTH found k)
            math(EXPR copy_count "${copy_count} + ${k}")
            list(APPEND problems ${found})
        endif()
        if(may_count AND l MATCHES "${ZEN_VALUES_COUNT_HINT}")
            zen_values_count("${bare}" c)
            if(NOT c STREQUAL "")
                zen_values_show("${c}" c)
                list(APPEND paragraph_counts "${rel}:${n}: a test count (\"${c}\") outside the population files names no commit and command that measured it -- name both beside it, or leave the number out")
            endif()
        endif()
    endforeach()
endforeach()

message(STATUS "code-values: ${id_count} values registered and read from their owners; "
               "${document_count} documents and ${source_count} sources read; ${marker_count} markers")
if(written_files)
    string(REPLACE ";" ", " shown "${written_files}")
    message(STATUS "code-values: rewrote the markers of ${shown}")
endif()
if(problems)
    list(LENGTH problems problem_count)
    string(REPLACE ";" "\n  " shown "${problems}")
    zen_values_show("${shown}" shown)
    message(FATAL_ERROR "code-values: ${problem_count} findings:\n  ${shown}")
endif()
message(STATUS "code-values: PASSED -- every marker says its owner's value, and no known value is copied unmarked")
