# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Joshua DeMoss
# The `manual` entry (manual/docs/manual.md): every manual in form and carried by a target, a pane's
# commands exactly its ids in tests/actions.txt, and every key marker its declared default.
#   cmake -P tests/check_manual.cmake   (from the root, or -DZEN_REPO=)

cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ZEN_REPO OR ZEN_REPO STREQUAL "")
    set(ZEN_REPO "${CMAKE_CURRENT_LIST_DIR}/..")
endif()
get_filename_component(ZEN_REPO "${ZEN_REPO}" ABSOLUTE)
if(NOT EXISTS "${ZEN_REPO}/AGENTS.md")
    message(FATAL_ERROR "manual: '${ZEN_REPO}' is not this repository's root (no AGENTS.md). "
                        "Pass -DZEN_REPO=<repository root>.")
endif()
include("${ZEN_REPO}/cmake/ZengineManual.cmake")

# The folders whose docs/ may hold a manual, by their kind in tests/folders.txt.
set(ZEN_MANUAL_KINDS feature host library)

# ---- the readings, one place each so the self-test exercises the real ones -------------------

# Text a CMake list can hold: the four characters it splits or escapes on, swapped for words no
# page spells (VM-CHECK-03).
function(zen_manual_swap text out)
    string(REPLACE "\r" "" text "${text}")
    string(REPLACE "\\" "<BS>" text "${text}")
    string(REPLACE ";" "<SC>" text "${text}")
    string(REPLACE "[" "<LB>" text "${text}")
    string(REPLACE "]" "<RB>" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

# The census as `office|id|key` entries, one per row (a key swapped as text is), from the lines of
# tests/actions.txt: `<office> <mode> <id> <key> <label>`.
function(zen_manual_census text out)
    zen_manual_swap("${text}" text)
    string(REPLACE "\n" ";" lines "${text}")
    set(entries "")
    foreach(line IN LISTS lines)
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        if(line MATCHES "^([a-z0-9.-]+) ([a-z0-9-]+) ([A-Za-z0-9_.-]+) ([^ ]+) (.+)$")
            list(APPEND entries "${CMAKE_MATCH_1}|${CMAKE_MATCH_3}|${CMAKE_MATCH_4}")
        else()
            list(APPEND entries "!${line}")
        endif()
    endforeach()
    set(${out} "${entries}" PARENT_SCOPE)
endfunction()

# Every way one manual is wrong. `page` is its path for the words, `stem` its file's name without
# `.md`, `text` its text, `census` the census's entries, `compiled` whether a target embeds it.
function(zen_manual_judge page stem text census compiled out)
    set(problems "")
    zengine_manual_split_text("${text}" m)
    foreach(r IN LISTS m_REFUSALS)
        list(APPEND problems "${page}: ${r}")
    endforeach()
    if(NOT m_OFFICE STREQUAL "" AND NOT m_OFFICE STREQUAL stem)
        list(APPEND problems "${page}: its title names `${m_OFFICE}` -- a manual is named by its office")
    endif()
    if(NOT compiled)
        list(APPEND problems "${page}: no target carries it -- `zengine_weave(... MANUAL <page>)` or `zengine_manual(<target> <scope> <page>)` names a manual")
    endif()
    # A PANE'S COMMANDS ARE EXACTLY ITS DECLARED IDS, in every mode the census drove.
    set(declared "")
    foreach(entry IN LISTS census)
        if(entry MATCHES "^${stem}\\|([^|]+)\\|")
            list(APPEND declared "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    if(declared)
        list(REMOVE_DUPLICATES declared)
        set(commands "")
        if(m_COUNT GREATER 0)
            math(EXPR last "${m_COUNT} - 1")
            foreach(i RANGE ${last})
                if(m_GROUP_${i} MATCHES "^Commands( (in|on) .*)?$" AND
                   NOT m_KEY_${i} MATCHES "^commands(-|$)")
                    list(APPEND commands "${m_KEY_${i}}")
                endif()
            endforeach()
        endif()
        foreach(id IN LISTS declared)
            if(NOT id IN_LIST commands)
                list(APPEND problems "${page}: `${id}` is an action ${stem} declares, and its manual has no section for it")
            endif()
        endforeach()
        foreach(id IN LISTS commands)
            if(NOT id IN_LIST declared)
                list(APPEND problems "${page}: `${id}` has a section, and ${stem} declares no such action")
            endif()
        endforeach()
    endif()
    set(${out} "${problems}" PARENT_SCOPE)
endfunction()

# Every key marker in a page whose key is not a default the census holds for its id.
function(zen_manual_markers page text census out)
    set(problems "")
    zen_manual_swap("${text}" text)
    string(REPLACE "\n" ";" lines "${text}")
    set(line_no 0)
    foreach(line IN LISTS lines)
        math(EXPR line_no "${line_no} + 1")
        string(REGEX MATCHALL "<!-- key [A-Za-z0-9_.-]+ -->[^<]*(<[LRSB][BC]>[^<]*)*<!-- /key -->"
               found "${line}")
        foreach(marker IN LISTS found)
            string(REGEX REPLACE "^<!-- key ([A-Za-z0-9_.-]+) -->.*$" "\\1" id "${marker}")
            string(REGEX REPLACE "^<!-- key [A-Za-z0-9_.-]+ -->(.*)<!-- /key -->$" "\\1" key "${marker}")
            string(REPLACE "`" "" key "${key}")
            set(known "")
            foreach(entry IN LISTS census)
                if(entry MATCHES "^[^|]+\\|([^|]+)\\|(.*)$" AND CMAKE_MATCH_1 STREQUAL id)
                    list(APPEND known "${CMAKE_MATCH_2}")
                endif()
            endforeach()
            if(NOT known)
                list(APPEND problems "${page}:${line_no}: a key marker names `${id}`, which no shipped pane declares in tests/actions.txt")
            elseif(key STREQUAL "unbound" OR NOT key IN_LIST known)
                string(REPLACE ";" "', '" said "${known}")
                list(APPEND problems "${page}:${line_no}: the key marker for `${id}` says '${key}', and the census declares '${said}'")
            endif()
        endforeach()
    endforeach()
    set(${out} "${problems}" PARENT_SCOPE)
endfunction()

# ---- the self-test (VM-CHECK-01): make it say NO, and make it say YES ------------------------
set(st_census_text "# a census\nt.pane browse t.go g go\nt.pane browse t.stop shift+s stop\nt.pane list t.stop unbound stop\n")
zen_manual_census("${st_census_text}" st_census)
if(NOT st_census STREQUAL "t.pane|t.go|g;t.pane|t.stop|shift+s;t.pane|t.stop|unbound")
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- the census read as '${st_census}'")
endif()
set(st_command "\n\nDoes it.\n\n- **Takes:** it.\n- **Answers:** it.\n- **Refuses:** nothing.\n- **Example:** <!-- key t.go -->`g`<!-- /key -->.\n")
set(st_head "# t.pane -- the test pane\n\n**Manual.** A pane.\n\n## About\n\nIt is.\n\n## Use\n\nUse it.\n\n## Commands\n\n### `t.go`${st_command}")
set(st_good "${st_head}\n### `t.stop`${st_command}")
zen_manual_judge("good" "t.pane" "${st_good}" "${st_census}" ON st_problems)
zen_manual_markers("good" "${st_good}" "${st_census}" st_marks)
if(st_problems OR st_marks)
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- a page in form was refused: ${st_problems} ${st_marks}")
endif()
zen_manual_judge("missing" "t.pane" "${st_head}" "${st_census}" ON st_problems)
if(NOT st_problems MATCHES "`t.stop` is an action t.pane declares, and its manual has no section for it")
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- a page missing a command passed: '${st_problems}'")
endif()
string(REPLACE "`g`<!-- /key -->" "`h`<!-- /key -->" st_wrong "${st_good}")
zen_manual_markers("wrong" "${st_wrong}" "${st_census}" st_marks)
if(NOT st_marks MATCHES "the key marker for `t.go` says 'h', and the census declares 'g'")
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- a marker naming the wrong key passed: '${st_marks}'")
endif()
zen_manual_markers("unbound" "x <!-- key t.stop -->`unbound`<!-- /key --> [y]" "${st_census}" st_marks)
if(NOT st_marks MATCHES "the key marker for `t.stop` says 'unbound'")
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- a marker on an unbound id passed: '${st_marks}'")
endif()
zen_manual_markers("bracket" "x <!-- key t.go -->`[`<!-- /key -->" "t.pane|t.go|<LB>" st_marks)
if(st_marks)
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- a bracket key read wrong: '${st_marks}'")
endif()
string(REPLACE "- **Refuses:** nothing.\n" "" st_short "${st_good}")
zen_manual_judge("short" "t.pane" "${st_short}" "" ON st_problems)
if(NOT st_problems MATCHES "needs its four lines in order")
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- a command without its Refuses line passed: '${st_problems}'")
endif()
zen_manual_judge("loose" "t.pane" "${st_good}" "" OFF st_problems)
if(NOT st_problems MATCHES "no target carries it")
    message(FATAL_ERROR "manual: SELF-TEST FAILED -- a page no target carries passed")
endif()

# ---- the tree ---------------------------------------------------------------------------------
file(READ "${ZEN_REPO}/tests/actions.txt" census_text)
zen_manual_census("${census_text}" census)
set(problems "")
foreach(entry IN LISTS census)
    if(entry MATCHES "^!(.*)$")
        list(APPEND problems "tests/actions.txt: '${CMAKE_MATCH_1}' is not `office mode id key label`")
    endif()
endforeach()
if(NOT census)
    message(FATAL_ERROR "manual: tests/actions.txt holds no row; an empty census holds nothing (VM-POP-01)")
endif()

# The pages a target embeds: each `MANUAL <page>` and `zengine_manual(<target> <scope> <page>)`
# in a CMakeLists.txt, relative to that file's folder or `${PROJECT_SOURCE_DIR}`.
file(GLOB_RECURSE lists RELATIVE "${ZEN_REPO}" "${ZEN_REPO}/CMakeLists.txt")
list(FILTER lists EXCLUDE REGEX "^(build(-[^/]*)?|cmake-build[^/]*|out|quarry|_install)/|/_deps/|third_party/")
set(compiled_pages "")
foreach(cmake_list IN LISTS lists)
    file(READ "${ZEN_REPO}/${cmake_list}" body)
    get_filename_component(dir "${cmake_list}" DIRECTORY)
    string(REGEX MATCHALL "(MANUAL[ \t\n]+|zengine_manual\\([^ \t\n)]+[ \t\n]+[A-Z]+[ \t\n]+)[^ \t\n)]+" named "${body}")
    foreach(one IN LISTS named)
        string(REGEX REPLACE "^.*[ \t\n]([^ \t\n]+)$" "\\1" path "${one}")
        string(REPLACE "\${PROJECT_SOURCE_DIR}" "${ZEN_REPO}" path "${path}")
        if(NOT IS_ABSOLUTE "${path}")
            set(path "${ZEN_REPO}/${dir}/${path}")
        endif()
        get_filename_component(path "${path}" ABSOLUTE)
        file(RELATIVE_PATH path "${ZEN_REPO}" "${path}")
        list(APPEND compiled_pages "${path}")
    endforeach()
endforeach()

file(STRINGS "${ZEN_REPO}/tests/folders.txt" rows REGEX "^[^#]")
set(pages "")
set(tutorials "")
foreach(row IN LISTS rows)
    if(row MATCHES "^([^ \t]+)[ \t]+([a-z]+)[ \t]*$" AND CMAKE_MATCH_2 IN_LIST ZEN_MANUAL_KINDS)
        set(folder "${CMAKE_MATCH_1}")
        file(GLOB_RECURSE found RELATIVE "${ZEN_REPO}" "${ZEN_REPO}/${folder}/*.md")
        foreach(md IN LISTS found)
            if(md MATCHES "/docs/tutorials/")
                list(APPEND tutorials "${md}")
            elseif(md MATCHES "(^|/)docs/[a-z0-9-]+(\\.[a-z0-9-]+)+\\.md$")
                list(APPEND pages "${md}")
            endif()
        endforeach()
    endif()
endforeach()
if(NOT pages)
    message(FATAL_ERROR "manual: no manual found under a feature's, the host's or a library's docs/; "
                        "an empty population is red (VM-POP-01)")
endif()

set(offices "")
foreach(page IN LISTS pages)
    get_filename_component(name "${page}" NAME)
    string(REGEX REPLACE "\\.md$" "" stem "${name}")
    if(stem IN_LIST offices)
        list(APPEND problems "${page}: a second manual for `${stem}`")
    endif()
    list(APPEND offices "${stem}")
    file(READ "${ZEN_REPO}/${page}" text)
    set(compiled OFF)
    if(page IN_LIST compiled_pages)
        set(compiled ON)
    endif()
    zen_manual_judge("${page}" "${stem}" "${text}" "${census}" ${compiled} found)
    list(APPEND problems ${found})
    zen_manual_markers("${page}" "${text}" "${census}" found)
    list(APPEND problems ${found})
endforeach()
foreach(page IN LISTS tutorials)
    file(READ "${ZEN_REPO}/${page}" text)
    zen_manual_markers("${page}" "${text}" "${census}" found)
    list(APPEND problems ${found})
endforeach()
# An office the census holds and no manual names is not refused here: a pane's page is held to its
# declared ids from the day the page exists.

list(LENGTH pages page_count)
list(LENGTH tutorials tutorial_count)
list(LENGTH census row_count)
message(STATUS "manual: ${page_count} manual(s) and ${tutorial_count} tutorial page(s) read against "
               "${row_count} census row(s)")
if(problems)
    list(LENGTH problems problem_count)
    string(REPLACE ";" "\n  " shown "${problems}")
    string(REPLACE "<LB>" "[" shown "${shown}")
    string(REPLACE "<RB>" "]" shown "${shown}")
    message(FATAL_ERROR "manual FAILED: ${problem_count} problem(s):\n  ${shown}")
endif()
message(STATUS "manual: PASSED -- every manual is in form and carried by a target, every pane's "
               "commands are its declared ids, and every key marker names its declared default")
