# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Joshua DeMoss
#
# The `folder_map` entry (docs/contributing/build-and-test.md): tests/folders.txt names every
# top-level folder and its kind; each feature, the host and each library holds a README.md and an
# AGENTS.md router within the law check's router budget; each file under agents/ but the decision
# records is routed by one router's `## Law`, each CTest entry claimed by one `## Suites`.
#   cmake -P tests/check_folder_map.cmake    (from the repository root, or -DZEN_REPO=<repo>)

cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ZEN_REPO OR ZEN_REPO STREQUAL "")
    set(ZEN_REPO "${CMAKE_CURRENT_LIST_DIR}/..")
endif()
get_filename_component(ZEN_REPO "${ZEN_REPO}" ABSOLUTE)
if(NOT EXISTS "${ZEN_REPO}/AGENTS.md")
    message(FATAL_ERROR "folder-map: '${ZEN_REPO}' is not this repository's root "
                        "(no AGENTS.md). Pass -DZEN_REPO=<repository root>.")
endif()

# The kinds a row may name, the kinds that hold a front page and a router, and the top-level names
# that are a tool's or a build's and never the repository's.
set(ZEN_MAP_KINDS feature host library examples build tests tools docs law quarry repository)
set(ZEN_MAP_ROUTED_KINDS feature host library)
set(ZEN_MAP_NOT_FOLDERS "^([.](git|idea|vscode|claude|cache)|__pycache__|build|out|_install)$|^build-|^cmake-build")
set(ZEN_MAP_ROOT_SECTION "Read this, then route")

# The router budget and the line width are the law check's (AGENTS.md, rule i), read from it.
file(READ "${ZEN_REPO}/tests/check_law_register.cmake" law_check)
if(NOT law_check MATCHES "set\\(ZEN_LAW_ROUTER_BYTES ([0-9]+)\\)")
    message(FATAL_ERROR "folder-map: no ZEN_LAW_ROUTER_BYTES in tests/check_law_register.cmake")
endif()
set(ZEN_MAP_ROUTER_BYTES ${CMAKE_MATCH_1})
if(NOT law_check MATCHES "set\\(ZEN_LAW_LINE_BYTES ([0-9]+)\\)")
    message(FATAL_ERROR "folder-map: no ZEN_LAW_LINE_BYTES in tests/check_law_register.cmake")
endif()
set(ZEN_MAP_LINE_BYTES ${CMAKE_MATCH_1})

# ---- the readings, one place each so the self-test exercises the real ones -------------------

# Markdown as one string no character of which reshapes a CMake list (VM-CHECK-03): `;` and `\`
# dropped (neither is in a path or an entry name), `[` and `]` swapped for two control characters.
string(ASCII 2 ZEN_MAP_STX)
string(ASCII 3 ZEN_MAP_ETX)
function(zen_map_swap text out)
    string(REPLACE "\r" "" text "${text}")
    string(REPLACE ";" "" text "${text}")
    string(REPLACE "\\" "" text "${text}")
    string(REPLACE "[" "${ZEN_MAP_STX}" text "${text}")
    string(REPLACE "]" "${ZEN_MAP_ETX}" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()
function(zen_map_read path out)
    file(READ "${path}" text)
    zen_map_swap("${text}" text)
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

# The text of the `## <title>` section: from the line after its heading to the next `## ` heading.
function(zen_map_section text title out)
    set(${out} "" PARENT_SCOPE)
    string(FIND "\n${text}" "\n## ${title}\n" at)
    if(at EQUAL -1)
        return()
    endif()
    string(LENGTH "## ${title}\n" skip)
    math(EXPR at "${at} + ${skip}")
    string(SUBSTRING "${text}" ${at} -1 rest)
    string(FIND "\n${rest}" "\n## " end)
    if(NOT end EQUAL -1)
        string(SUBSTRING "${rest}" 0 ${end} rest)
    endif()
    set(${out} "${rest}" PARENT_SCOPE)
endfunction()

# The repository paths a section's Markdown links name, resolved from the router's folder `dir`
# (empty at the root); an anchor is dropped, a link to a URL or above the root is not a path.
function(zen_map_link_targets section dir out)
    set(found "")
    string(REGEX MATCHALL "${ZEN_MAP_ETX}[(][^)# \t\n]+" links "${section}")
    foreach(link IN LISTS links)
        string(SUBSTRING "${link}" 2 -1 target)
        if(target MATCHES "^[a-z][a-z0-9+.-]*:" OR target MATCHES "^/")
            continue()
        endif()
        if(dir STREQUAL "")
            set(joined "${target}")
        else()
            set(joined "${dir}/${target}")
        endif()
        get_filename_component(abs "${joined}" ABSOLUTE BASE_DIR "${ZEN_REPO}")
        file(RELATIVE_PATH norm "${ZEN_REPO}" "${abs}")
        if(norm MATCHES "^[.][.]")
            continue()
        endif()
        list(APPEND found "${norm}")
    endforeach()
    set(${out} "${found}" PARENT_SCOPE)
endfunction()

# The entries a section claims: on each line opening `- \``, the backticked names before the
# line's first dash of explanation (` — ` or ` -- `), those of them the population declares.
function(zen_map_claims section population out)
    set(found "")
    string(REPLACE "\n" ";" lines "${section}")
    foreach(line IN LISTS lines)
        if(NOT line MATCHES "^- `")
            continue()
        endif()
        string(REGEX REPLACE " (—|--) .*$" "" head "${line}")
        string(REGEX MATCHALL "`[^`]+`" names "${head}")
        foreach(name IN LISTS names)
            string(REGEX REPLACE "^`(.*)`$" "\\1" name "${name}")
            if(name IN_LIST population)
                list(APPEND found "${name}")
            endif()
        endforeach()
    endforeach()
    set(${out} "${found}" PARENT_SCOPE)
endfunction()

# ---- the self-test (VM-CHECK-01) --------------------------------------------------------------
zen_map_swap("# r\n\n## Law\n\n- [a](../agents/a.md) and [b](../agents/b.md#x)\n- see https://x.y/agents/c.md\n\n## Suites\n\n- `e1`, `e2` -- what `e3` is\n- `e4` — the one\nThe shared `e5`, a key `[` alone\n- `e7` -- after it\n\n## Pages\n\n- [c](../agents/c.md)\n- `e6` -- not in its section\n" st_text)
zen_map_section("${st_text}" "Law" st_law)
zen_map_link_targets("${st_law}" "feature" st_links)
if(NOT st_links STREQUAL "agents/a.md;agents/b.md")
    message(FATAL_ERROR "folder-map: SELF-TEST FAILED -- the Law section's links read as '${st_links}', "
                        "want 'agents/a.md;agents/b.md' (a URL and another section's link are no claim)")
endif()
zen_map_section("${st_text}" "Suites" st_suites)
zen_map_claims("${st_suites}" "e1;e2;e3;e4;e5;e6;e7" st_claims)
if(NOT st_claims STREQUAL "e1;e2;e4;e7")
    message(FATAL_ERROR "folder-map: SELF-TEST FAILED -- the Suites section claims '${st_claims}', "
                        "want 'e1;e2;e4;e7' (a name after the dash, in prose or in another section is "
                        "no claim, and a stray bracket hides none)")
endif()
string(MD5 st_a "agents/w/a.md")
string(MD5 st_b "agents/w_a.md")
if(st_a STREQUAL st_b)
    message(FATAL_ERROR "folder-map: SELF-TEST FAILED -- two registers share a tally key")
endif()
zen_map_section("${st_text}" "Missing" st_missing)
if(NOT st_missing STREQUAL "")
    message(FATAL_ERROR "folder-map: SELF-TEST FAILED -- a section that is not there read as text")
endif()
if(NOT "__pycache__" MATCHES "${ZEN_MAP_NOT_FOLDERS}" OR NOT "build-win" MATCHES "${ZEN_MAP_NOT_FOLDERS}"
   OR "builder" MATCHES "${ZEN_MAP_NOT_FOLDERS}" OR ".github" MATCHES "${ZEN_MAP_NOT_FOLDERS}")
    message(FATAL_ERROR "folder-map: SELF-TEST FAILED -- ZEN_MAP_NOT_FOLDERS takes a folder of the "
                        "repository, or leaves a build's")
endif()

set(problems "")

# ---- the rows ---------------------------------------------------------------------------------
file(STRINGS "${ZEN_REPO}/tests/folders.txt" rows REGEX "^[^#]")
set(listed "")
set(routed "")
foreach(row IN LISTS rows)
    if(NOT row MATCHES "^([^ \t]+)[ \t]+([a-z]+)[ \t]*$")
        list(APPEND problems "tests/folders.txt: '${row}' is not `folder kind`")
        continue()
    endif()
    set(folder "${CMAKE_MATCH_1}")
    set(kind "${CMAKE_MATCH_2}")
    if(NOT kind IN_LIST ZEN_MAP_KINDS)
        string(REPLACE ";" ", " kinds "${ZEN_MAP_KINDS}")
        list(APPEND problems "tests/folders.txt: ${folder}'s kind '${kind}' is none of ${kinds}")
    endif()
    if(folder IN_LIST listed)
        list(APPEND problems "tests/folders.txt names ${folder} twice")
    endif()
    list(APPEND listed "${folder}")
    if(NOT IS_DIRECTORY "${ZEN_REPO}/${folder}")
        list(APPEND problems "tests/folders.txt names ${folder}, which is no folder of this repository")
    elseif(kind IN_LIST ZEN_MAP_ROUTED_KINDS)
        list(APPEND routed "${folder}")
        foreach(page README.md AGENTS.md)
            if(NOT EXISTS "${ZEN_REPO}/${folder}/${page}")
                list(APPEND problems "${folder}/ is a ${kind} and holds no ${page}")
            endif()
        endforeach()
    endif()
endforeach()
list(LENGTH listed listed_count)
if(listed_count EQUAL 0)
    message(FATAL_ERROR "folder-map: tests/folders.txt names no folder; an empty map holds nothing (VM-POP-01)")
endif()

file(GLOB top RELATIVE "${ZEN_REPO}" "${ZEN_REPO}/*" "${ZEN_REPO}/.*")
set(present 0)
foreach(entry IN LISTS top)
    if(NOT IS_DIRECTORY "${ZEN_REPO}/${entry}" OR entry MATCHES "${ZEN_MAP_NOT_FOLDERS}")
        continue()
    endif()
    math(EXPR present "${present} + 1")
    if(NOT entry IN_LIST listed)
        list(APPEND problems "${entry}/ is a top-level folder tests/folders.txt does not name -- give it a row and a kind")
    endif()
endforeach()

# ---- the routers: the root's routing section, and every listed folder's AGENTS.md ------------
set(routers AGENTS.md)
foreach(folder IN LISTS listed)
    if(EXISTS "${ZEN_REPO}/${folder}/AGENTS.md")
        list(APPEND routers "${folder}/AGENTS.md")
    endif()
endforeach()

file(STRINGS "${ZEN_REPO}/tests/test_population.txt" pop_rows REGEX "^[^#]")
set(population "")
foreach(row IN LISTS pop_rows)
    string(REGEX REPLACE "#.*$" "" row "${row}")
    string(STRIP "${row}" row)
    if(row MATCHES "^([^ \t]+)[ \t]")
        list(APPEND population "${CMAKE_MATCH_1}")
    endif()
endforeach()
list(REMOVE_DUPLICATES population)
file(GLOB_RECURSE registers RELATIVE "${ZEN_REPO}" "${ZEN_REPO}/agents/*.md")
list(FILTER registers EXCLUDE REGEX "^agents/decisions/")
list(LENGTH population population_count)
list(LENGTH registers register_count)
if(population_count EQUAL 0 OR register_count EQUAL 0)
    message(FATAL_ERROR "folder-map: ${population_count} CTest entries and ${register_count} registers "
                        "read; an empty population is a failure, not a pass (VM-POP-01)")
endif()

foreach(router IN LISTS routers)
    zen_map_read("${ZEN_REPO}/${router}" text)
    if(router STREQUAL "AGENTS.md")
        set(dir "")
        zen_map_section("${text}" "${ZEN_MAP_ROOT_SECTION}" law)
        set(suites "${law}")
        if(law STREQUAL "")
            list(APPEND problems "AGENTS.md has no `## ${ZEN_MAP_ROOT_SECTION}` section to route from")
        endif()
    else()
        get_filename_component(dir "${router}" DIRECTORY)
        zen_map_section("${text}" "Law" law)
        zen_map_section("${text}" "Suites" suites)
        foreach(title Law Suites)
            string(FIND "\n${text}" "\n## ${title}\n" at)
            if(at EQUAL -1)
                list(APPEND problems "${router} has no `## ${title}` section")
            endif()
        endforeach()
        # the budget and the width the law check gives a router
        file(READ "${ZEN_REPO}/${router}" raw)
        string(REPLACE "\r" "" raw "${raw}")
        string(LENGTH "${raw}" bytes)
        if(bytes GREATER ZEN_MAP_ROUTER_BYTES)
            list(APPEND problems "${router} is ${bytes} bytes (a router is at most ${ZEN_MAP_ROUTER_BYTES})")
        endif()
        string(REPLACE ";" "," raw "${raw}")
        string(REPLACE "[" "(" raw "${raw}")
        string(REPLACE "]" ")" raw "${raw}")
        string(REPLACE "\\" "/" raw "${raw}")
        string(REPLACE "\n" ";" raw_lines "${raw}")
        set(n 0)
        foreach(line IN LISTS raw_lines)
            math(EXPR n "${n} + 1")
            string(LENGTH "${line}" len)
            if(len GREATER ZEN_MAP_LINE_BYTES AND NOT line MATCHES "^\\|")
                list(APPEND problems "${router}:${n} is ${len} bytes (at most ${ZEN_MAP_LINE_BYTES}, table rows excepted)")
            endif()
        endforeach()
    endif()
    zen_map_link_targets("${law}" "${dir}" targets)
    list(REMOVE_DUPLICATES targets)
    foreach(target IN LISTS targets)
        if(target IN_LIST registers)
            string(MD5 key "${target}")
            list(APPEND routed_by_${key} "${router}")
        endif()
    endforeach()
    zen_map_claims("${suites}" "${population}" claimed)
    list(REMOVE_DUPLICATES claimed)
    foreach(entry IN LISTS claimed)
        list(APPEND claimed_by_${entry} "${router}")
    endforeach()
endforeach()

foreach(register IN LISTS registers)
    string(MD5 key "${register}")
    list(LENGTH routed_by_${key} count)
    if(count EQUAL 0)
        list(APPEND problems "${register} is routed by no router: link it from the `## Law` section of the router of the folder it serves")
    elseif(count GREATER 1)
        string(REPLACE ";" ", " by "${routed_by_${key}}")
        list(APPEND problems "${register} is routed by ${count} routers (${by}), and one routes it")
    endif()
endforeach()
foreach(entry IN LISTS population)
    list(LENGTH claimed_by_${entry} count)
    if(count EQUAL 0)
        list(APPEND problems "CTest entry ${entry} is claimed by no router: a `- \`${entry}\`` line in the `## Suites` section of the router of the folder it witnesses")
    elseif(count GREATER 1)
        string(REPLACE ";" ", " by "${claimed_by_${entry}}")
        list(APPEND problems "CTest entry ${entry} is claimed by ${count} routers (${by}), and one claims it")
    endif()
endforeach()

list(LENGTH routers router_count)
list(LENGTH routed routed_count)
message(STATUS "folder-map: ${listed_count} folders listed and ${present} present; ${routed_count} "
               "are a feature, the host or a library; ${router_count} routers read with the root's; "
               "${register_count} registers and ${population_count} CTest entries routed")
if(problems)
    list(LENGTH problems problem_count)
    string(REPLACE ";" "\n  " shown "${problems}")
    message(FATAL_ERROR "folder-map FAILED: ${problem_count} problem(s):\n  ${shown}")
endif()
message(STATUS "folder-map: PASSED -- every folder is mapped, every feature, the host and every "
               "library holds a front page and a router, and every register and CTest entry is routed once")
