// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Joshua DeMoss
#ifndef ZENGINE_FLOW_GENERATE_HPP
#define ZENGINE_FLOW_GENERATE_HPP

#include "flow/native.hpp"

#include <limits>
#include <sstream>
#include <string>
#include <string_view>

namespace zengine::flow {

inline std::string cpp_string(std::string_view text) {
    std::string out = "std::string(\"";
    for (char byte : text) {
        const auto c = static_cast<unsigned char>(byte);
        if (c >= 32 && c <= 126 && c != '\\' && c != '"') out += byte;
        else {
            out += '\\';
            out += static_cast<char>('0' + ((c >> 6u) & 7u));
            out += static_cast<char>('0' + ((c >> 3u) & 7u));
            out += static_cast<char>('0' + (c & 7u));
        }
    }
    return out + "\", " + std::to_string(text.size()) + ")";
}

inline std::string cpp_constant(const loom::Cell& cell) {
    if (cell.kind() == loom::Kind::Bool)
        return std::string("loom::Cell::boolean(") + (cell.as_bool() ? "true)" : "false)");
    if (cell.kind() != loom::Kind::Int)
        throw std::invalid_argument("composition constants must be Int or Bool");
    const auto value = cell.as_int();
    return "loom::Cell::integer(" + (value == std::numeric_limits<std::int64_t>::min() ?
        std::string("(-9223372036854775807LL - 1)") : std::to_string(value) + "LL") + ")";
}

inline std::string generate_cpp(const maker::Definition& source) {
    // Round-trip through the owning admission before indexing or emitting anything.
    auto admitted = maker::read_definition(maker::definition_bytes(source));
    if (!admitted) throw std::invalid_argument(admitted.reason);
    const auto& definition = admitted.definition;
    std::ostringstream out;
    out << "// Generated by Zengine Flow C++ format 1.\n"
           "// Edit the definition and regenerate to retain the verified return path.\n"
           "// Handwritten changes are allowed; recovery then refuses to claim equivalence.\n"
           "#include <flow/native.hpp>\n#include <zen/kernel/export.hpp>\n\n"
           "namespace flow = zengine::flow;\nnamespace op = zengine::op;\n"
           "namespace maker = zengine::maker;\n\n"
           "static const maker::Definition& definition() {\n"
           "    static const auto value = flow::definition_from_hex(\n"
           "// FLOW_DEFINITION_BEGIN\n";
    const auto encoded = hex(maker::definition_bytes(definition));
    for (std::size_t i = 0; i < encoded.size(); i += 96)
        out << "        \"" << encoded.substr(i, 96) << "\"\n";
    out << "// FLOW_DEFINITION_END\n    );\n    return value;\n}\n\n";
    for (std::size_t t = 0; t < definition.on.size(); ++t) {
        const auto& trigger = definition.on[t];
        out << "// Trigger " << t << ": identifiers below are length-preserving C++ strings.\n"
            << "static loom::Value trigger_" << t
            << "(op::OperatorHost host, [[maybe_unused]] const loom::Value& inputs) {\n"
            << "    const auto identity = " << cpp_string(definition.trigger_identity(trigger)) << ";\n";
        for (std::size_t n = 0; n < trigger.body.nodes.size(); ++n) {
            const auto& node = trigger.body.nodes[n];
            out << "    flow::Step step_" << n << "(host, identity, " << n << ", "
                << cpp_string(node.identity) << ", " << node.authored_in << "ULL, "
                << node.authored_out << "ULL);\n";
            for (std::size_t a = 0; a < node.arguments.size(); ++a) {
                const auto& binding = node.arguments[a];
                out << "    step_" << n;
                switch (binding.from()) {
                case op::Binding::From::Input:
                    out << ".input(" << a << ", inputs, " << cpp_string(binding.input_name()) << ");\n";
                    break;
                case op::Binding::From::Node:
                    out << ".value(" << a << ", *answer_" << binding.node_index() << ".at(0));\n";
                    break;
                case op::Binding::From::Constant:
                    out << ".value(" << a << ", " << cpp_constant(binding.constant_cell()) << ");\n";
                    break;
                }
            }
            out << "    [[maybe_unused]] auto answer_" << n << " = step_" << n << ".run();\n";
        }
        out << "    return answer_" << trigger.body.result_node << ";\n}\n\n";
    }
    out << "static loom::Value run(std::size_t index, [[maybe_unused]] op::OperatorHost host,\n"
           "                       [[maybe_unused]] const loom::Value& inputs) {\n"
           "    switch (index) {\n";
    for (std::size_t i = 0; i < definition.on.size(); ++i)
        out << "    case " << i << ": return trigger_" << i << "(host, inputs);\n";
    out << "    default: throw std::invalid_argument(\"unknown trigger index\");\n    }\n}\n\n"
           "static ZengineOperatorStatus describe(ZenByteSink sink) {\n"
           "    try {\n        flow::emit_bytes(sink, maker::definition_bytes(definition()));\n"
           "        return ZENGINE_OP_OK;\n    } catch (...) { return ZENGINE_OP_ERR_HOST_FAILED; }\n}\n"
           "static ZengineOperatorStatus execute(std::size_t index,\n"
           "        const ZengineOperatorHostApiV1* steps, const std::uint8_t* bytes, std::size_t size,\n"
           "        ZenByteSink answer, ZenByteSink reason) {\n"
           "    try { return flow::execute_native(definition(), &run, index, steps, bytes, size, answer, reason); }\n"
           "    catch (...) { return ZENGINE_OP_ERR_HOST_FAILED; }\n}\n\n"
           "extern \"C\" ZEN_KERNEL_EXPORT const ZengineFlowArtifactV1* zengine_flow_artifact() {\n"
           "    static const ZengineFlowArtifactV1 table{ZENGINE_FLOW_ABI_VERSION, &describe, &execute};\n"
           "    return &table;\n}\n\n"
           "class GeneratedWeave final : public flow::NativeWeave {\n"
           "public:\n    GeneratedWeave() : NativeWeave(::definition()) {}\n};\n"
           "ZENGINE_OPERATOR_CONSUMER();\nZEN_EXPORT_WEAVE(GeneratedWeave)\n";
    return out.str();
}

inline maker::Definition recover_cpp(std::string_view source) {
    constexpr std::string_view begin = "// FLOW_DEFINITION_BEGIN\n";
    constexpr std::string_view end = "// FLOW_DEFINITION_END\n";
    const auto first = source.find(begin), last = source.find(end);
    if (first == std::string_view::npos || last == std::string_view::npos || last <= first)
        throw std::invalid_argument("no retained Flow definition");
    std::string encoded;
    std::istringstream lines(std::string(source.substr(first + begin.size(), last - first - begin.size())));
    std::string line;
    while (std::getline(lines, line)) {
        if (line.size() < 10 || line.substr(0, 9) != "        \"" || line.back() != '"')
            throw std::invalid_argument("retained definition was edited");
        encoded += line.substr(9, line.size() - 10);
    }
    auto definition = definition_from_hex(encoded);
    if (generate_cpp(definition) != source)
        throw std::invalid_argument("generated C++ was edited or uses another generator version; "
                                    "the retained definition cannot describe those changes");
    return definition;
}

inline std::string generated_cmake() {
    return R"cmake(cmake_minimum_required(VERSION 3.16)
project(flow_generated LANGUAGES CXX)
find_package(zengine 0.1 CONFIG REQUIRED)
add_library(flow-generated SHARED generated.cpp)
target_compile_features(flow-generated PRIVATE cxx_std_20)
target_link_libraries(flow-generated PRIVATE zengine::flow loom::core loom::switchboard)
loom_weave_build_contract(flow-generated)
set_target_properties(flow-generated PROPERTIES PREFIX "")
)cmake";
}

} // namespace zengine::flow
#endif
