#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Joshua DeMoss
#
# THE WORKSHOP RESIDUES' APPLIER -- sheet -> applier -> proof (AGENTS.md rule o), for what
# the split left behind. The split (tools/workshop-split/) filed one .cpp per run of section
# banners, and the last run of each header held more than its banner named: the composition
# (`paint_panels`, `band_region`, `paint`) sat under the pane editor's banner in
# screen_pane_editor.cpp, and 36 functions after "Save and open" sat in weave_save.cpp. This
# applier gives those tails their banners and files them as the split would have.
#
# What it regenerates, and from which commit: everything is read AT THE START COMMIT with
# `git show`, never from the working tree, so a rerun converges.
#
#   grab-bags   the two headers gain a `// ----` banner above the first prototype of each new
#               run (RUNS below); the bodies from that function to the end of the run move,
#               verbatim, from the source .cpp into `workshop/<header>_<subject>.cpp`, the
#               `// WL-` pointer group above each body travelling with it (rule t); every
#               PROVEN BY spelling under the source .cpp that names a moved function, or a
#               name only a moved body uses, is re-pathed to the new file and the paragraph
#               re-wrapped at 98 bytes from the first line the change reached (rule i); each
#               touched file's `// Workshop law:` header is regenerated by the split's rule
#               (the register most cited on the file's own pointer lines, ties alphabetical,
#               `+N` the others); the logic target's source list gains the files.
#
#   python3 tools/workshop-residues/apply.py seed  grab-bags --repo . --start <commit>
#          writes tools/workshop-residues/sheet.tsv: one row per moved function -- the review.
#   python3 tools/workshop-residues/apply.py apply grab-bags --repo . --start <commit>
#          reads the sheet and writes the END files into the working tree.
#
# No body is rewritten: a moved definition is byte-for-byte the START text. prove.py checks
# that, the string literals, the headers (comments stripped, identical) and the registers.

import argparse
import collections
import os
import re
import subprocess
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
SPLIT = os.path.join(HERE, "..", "workshop-split")
sys.path.insert(0, SPLIT)
import cxx  # noqa: E402


def _load(name, path):
    import importlib.util
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# The split's applier, for the wrap, the law line, the paragraph walk and the SPDX header --
# loaded by path because both appliers are called apply.py.
split = _load("workshop_split_apply", os.path.join(SPLIT, "apply.py"))

# ---- THE RUNS: a banner added, and where its bodies go -----------------------------------
#
# One entry per banner this phase adds: the header and the source .cpp the split filed the
# tail into, the first function of the new run (the banner goes above its prototype's doc
# comment, and the run reaches to the next entry's first function in the same source or to
# the end of the file), the banner in the code's own words, the subject the file is named
# by, and the sentence the new file opens with.
BANNER_WIDTH = 92


def banner(indent, words):
    line = "%s// ---- %s " % (indent, words)
    return line + "-" * max(4, BANNER_WIDTH - len(line))


RUNS = [
    dict(header="workshop/screen.hpp", source="workshop/screen_pane_editor.cpp", first="paint_panels",
         subject="compose",
         banner=banner("", "THE COMPOSITION: every pane back to front, the bottom band, and the screen as planes"),
         desc="the composition: every presented pane back to front, one layer each, the bottom band as one "
              "published region, and the whole screen as one canvas of planes"),
    dict(header="workshop/weave.hpp", source="workshop/weave_save.cpp", first="create_object",
         subject="document",
         banner=banner("    ", "THE DOCUMENT'S GESTURES: the objects, the inspector, and what the tool says"),
         desc="the document's gestures: the object operations (make, delete, move and size, and what each "
              "says), the inspector's cursor, draft and selection, the workspace, the notice and the "
              "status line"),
    dict(header="workshop/weave.hpp", source="workshop/weave_save.cpp", first="refresh_external_rooms",
         subject="external",
         banner=banner("    ", "THE EXTERNAL PANE'S ROOM AND GESTURES: the grant, a press, a key, the wheel, text"),
         desc="the external pane's room and gestures: the room granted once per repaint and only when it "
              "changed, a press, a key, the wheel and text forwarded to the provider, and the selected "
              "pane put down"),
    dict(header="workshop/weave.hpp", source="workshop/weave_save.cpp", first="frontier_now",
         subject="run",
         banner=banner("    ", "THE RUN: what is true now, the picture published, and the way out"),
         desc="the run: the frontier and the clock read alive, the repaint that publishes the slots and "
              "then the picture, the one quit that writes the desk on the way out, and the draft-first "
              "sentence"),
]
CLASS_OF = {"workshop/weave.hpp": "WorkshopWeave"}
SHEET_COLUMNS = ["source", "name", "first_param", "pointer_first", "start_line", "end_line",
                 "pointer_ids", "destination", "banner"]
WRAP = split.WRAP


def dest_path(header, subject):
    return "workshop/%s_%s.cpp" % (os.path.basename(header)[:-4], subject)


def git_show(repo, commit, path):
    return split.git_show(repo, commit, path)


# ---- reading START -------------------------------------------------------------------------

def functions_of(text):
    """Every function defined at namespace scope in a .cpp (an out-of-line member's
    qualified name reads as its last part), in file order."""
    decls, _ = cxx.declarations(text)
    return [d for d in decls if d.kind == "function" and d.defined
            and not any(s and s[0].isupper() for s in d.scope)]


class Source:
    """One of the two grab-bag .cpp files, as it is at START."""

    def __init__(self, repo, commit, path):
        self.path = path
        self.text = git_show(repo, commit, path)
        self.lines = self.text.split("\n")
        self.functions = functions_of(self.text)
        code = [n for n, _ in cxx.code_lines(self.text)]
        import bisect
        for d in self.functions:
            k = bisect.bisect_left(code, d.first_line)
            prev = code[k - 1] if k > 0 else 0
            d.pointer_lines = cxx.pointer_lines_between(self.lines, prev, d.first_line)
            d.pointer_ids = re.findall(r"WL-[A-Z]+-[0-9]+", "\n".join(self.lines[i - 1] for i in d.pointer_lines))
            d.unit_first = min(d.pointer_lines) if d.pointer_lines else d.first_line
            if d.scope != ["zengine::workshop"]:
                raise SystemExit("%s:%d %s is not directly in zengine::workshop" % (path, d.first_line, d.name))

    def runs(self):
        """[(run, [functions])] for this source, in START order."""
        mine = [r for r in RUNS if r["source"] == self.path]
        starts = []
        for r in mine:
            hits = [d for d in self.functions if d.name == r["first"]]
            if len(hits) != 1:
                raise SystemExit("%s: %d functions named %s" % (self.path, len(hits), r["first"]))
            starts.append((hits[0].first_line, r))
        starts.sort()
        out = []
        for i, (line, r) in enumerate(starts):
            end = starts[i + 1][0] if i + 1 < len(starts) else 10 ** 9
            out.append((r, [d for d in self.functions if line <= d.first_line < end]))
        return out


# ---- the sheet -----------------------------------------------------------------------------

def seed(repo, commit, out):
    rows = []
    for path in sorted({r["source"] for r in RUNS}):
        src = Source(repo, commit, path)
        for r, funcs in src.runs():
            for d in funcs:
                rows.append({"source": path, "name": d.name, "first_param": d.first_param,
                             "pointer_first": d.unit_first, "start_line": d.first_line,
                             "end_line": d.last_line, "pointer_ids": ",".join(d.pointer_ids),
                             "destination": dest_path(r["header"], r["subject"]), "banner": r["banner"].strip()})
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("# The Workshop residues' sheet, regenerated from %s by apply.py seed grab-bags; one row per moved body.\n" % commit)
        f.write("\t".join(SHEET_COLUMNS) + "\n")
        for r in rows:
            f.write("\t".join(str(r[c]) for c in SHEET_COLUMNS) + "\n")
    return rows


def read_sheet(path):
    rows = []
    with open(path, encoding="utf-8") as f:
        header = None
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if header is None:
                header = parts
                continue
            rows.append(dict(zip(header, parts)))
    for r in rows:
        for c in ("pointer_first", "start_line", "end_line"):
            r[c] = int(r[c])
    return rows


# ---- apply ---------------------------------------------------------------------------------

def insert_banner(header_text, run):
    """The header with the run's banner above the doc comment of its first prototype."""
    decls, _ = cxx.declarations(header_text)
    cls = CLASS_OF.get(run["header"])
    hits = [d for d in decls if d.kind == "function" and not d.defined and d.name == run["first"]
            and (not cls or (d.scope and d.scope[-1] == cls))]
    if len(hits) != 1:
        raise SystemExit("%s: %d prototypes named %s" % (run["header"], len(hits), run["first"]))
    lines = header_text.split("\n")
    k = hits[0].first_line - 1  # 0-based index of the prototype's first line
    while k > 0 and lines[k - 1].strip().startswith("//"):
        k -= 1
    if lines[k - 1].strip() != "":
        raise SystemExit("%s:%d: no blank line above the comment block of %s" % (run["header"], k, run["first"]))
    lines[k:k] = [run["banner"], ""]
    return "\n".join(lines)


def apply(repo, commit, sheet_path):
    rows = read_sheet(sheet_path)
    written = []
    by_source = collections.defaultdict(list)
    for r in rows:
        by_source[r["source"]].append(r)
    # 1. the headers
    for header in sorted({r["header"] for r in RUNS}):
        text = git_show(repo, commit, header)
        for r in RUNS:
            if r["header"] == header:
                text = insert_banner(text, r)
        split.write(repo, header, text)
        written.append(header)
    # 2. the sources and the new files
    new_files = []
    end_code_order = []  # files in START order of their first body, for the used-name rule
    for path in sorted(by_source):
        src = Source(repo, commit, path)
        at = {(d.first_line, d.last_line): d for d in src.functions}
        moved = []
        for r in by_source[path]:
            d = at.get((r["start_line"], r["end_line"]))
            if d is None or d.name != r["name"]:
                raise SystemExit("sheet row %s:%s-%s %s does not match START" % (path, r["start_line"], r["end_line"], r["name"]))
            moved.append((d, r))
        moved.sort(key=lambda dr: dr[0].first_line)
        # the source, its units cut from the bottom up
        lines = list(src.lines)
        for d, _ in reversed(moved):
            a, b = d.unit_first - 1, d.last_line
            if a > 0 and lines[a - 1].strip() == "":
                a -= 1
            del lines[a:b]
        text = "\n".join(lines)
        law = split.workshop_law_line([l for l in lines if cxx.POINTER_LINE.match(l)])
        if law:
            text = split.WORKSHOP_LAW.sub(law, text, count=1)
        split.write(repo, path, text)
        written.append(path)
        end_code_order.append(path)
        # the new files, one per destination, bodies in START order
        by_dest = collections.OrderedDict()
        for d, r in moved:
            by_dest.setdefault(r["destination"], []).append((d, r))
        for dest, items in by_dest.items():
            run = [x for x in RUNS if dest_path(x["header"], x["subject"]) == dest][0]
            out = [split.SPDX.rstrip("\n"), ""]
            sentence = ("The bodies of `%s`'s section -- %s -- compiled once into `zengine-workshop-logic` and "
                        "linked by the host and every suite; the declarations, the constants and the constexpr "
                        "functions stay in the header." % (os.path.basename(run["header"]), run["desc"]))
            out += ["// " + l for l in textwrap.wrap(sentence, width=WRAP - 3, break_on_hyphens=False)]
            pointers = []
            for d, _ in items:
                pointers += [src.lines[i - 1].strip() for i in d.pointer_lines]
            law = split.workshop_law_line(pointers)
            if law:
                out.append(law)
            out += ["", '#include "%s"' % os.path.basename(run["header"]), "", "namespace zengine::workshop {",
                    "", run["banner"].strip()]
            for d, _ in items:
                out += [""] + [src.lines[i - 1] for i in d.pointer_lines] + src.lines[d.first_line - 1:d.last_line]
            out += ["", "} // namespace zengine::workshop", ""]
            split.write(repo, dest, "\n".join(out))
            written.append(dest)
            new_files.append(dest)
            end_code_order.append(dest)
    # 3. the registers
    for reg, text in repath_registers(repo, commit, rows, end_code_order).items():
        split.write(repo, reg, text)
        written.append(reg)
    # 4. the CMake source list, between its markers, read from the working tree
    cm = os.path.join(repo, "workshop/CMakeLists.txt")
    with open(cm, encoding="utf-8") as f:
        cmt = f.read()
    a = cmt.index("add_library(zengine-workshop-logic STATIC\n") + len("add_library(zengine-workshop-logic STATIC\n")
    b = cmt.index("\n)", a)
    names = sorted(set(cmt[a:b].split()) | {os.path.basename(n) for n in new_files})
    cmt = cmt[:a] + "\n".join("    %s" % n for n in names) + cmt[b:]
    split.write(repo, "workshop/CMakeLists.txt", cmt)
    written.append("workshop/CMakeLists.txt")
    print("apply grab-bags: wrote %d files" % len(written))
    for w in written:
        print("  ", w)


# ---- the registers -------------------------------------------------------------------------

def split_segments(joined, source, path_re):
    """`source` segments in a joined PROVEN BY paragraph: (start, end, [spellings])."""
    out = []
    for m in path_re.finditer(joined):
        if m.group(1) != source:
            continue
        i = m.end()
        ids = []
        while True:
            mm = re.match(r"\s*`([^`]+)`", joined[i:])
            if not mm or mm.group(1).startswith('"') or mm.group(1).startswith("case"):
                break
            ids.append(mm.group(1))
            i += mm.end()
            sep = re.match(r"\s*,", joined[i:])
            if sep:
                i += sep.end()
                continue
            break
        out.append((m.start(), i, ids))
    return out


def spelling_matches(spelling, d):
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_:]*)\(([A-Za-z_][A-Za-z0-9_:]*)\)$", spelling)
    if m:
        return m.group(1).split("::")[-1] == d.name and d.first_param == m.group(2).split("::")[-1]
    return spelling.split("::")[-1] == d.name


def repath_registers(repo, commit, rows, end_code_order, report=None):
    sources = sorted({r["source"] for r in rows})
    path_re = re.compile(r"`(%s)`" % "|".join(re.escape(s) for s in sources))
    end_code = {}
    for f in end_code_order:
        with open(os.path.join(repo, f), encoding="utf-8") as fh:
            end_code[f] = cxx.strip_comments_and_blanks(fh.read())
    starts = {s: Source(repo, commit, s) for s in sources}
    moved_of = {}
    for s in sources:
        keyed = {(r["start_line"], r["end_line"]): r["destination"] for r in rows if r["source"] == s}
        moved_of[s] = [(d, keyed[(d.first_line, d.last_line)]) for d in starts[s].functions
                       if (d.first_line, d.last_line) in keyed]
    decisions = []

    def destinations_for(spelling, source):
        stays = [d for d in starts[source].functions if spelling_matches(spelling, d)
                 and not any(spelling_matches(spelling, m) and m is d for m, _ in moved_of[source])]
        hits = [dest for d, dest in moved_of[source] if spelling_matches(spelling, d)]
        out = []
        if stays:
            out.append(source)
        for dest in hits:
            if dest not in out:
                out.append(dest)
        if out:
            return out, "declared"
        parts = cxx.IDENT.findall(spelling)

        def has(code):
            return all(re.search(r"(^|[^A-Za-z0-9_])%s([^A-Za-z0-9_]|$)" % re.escape(p), code) for p in parts)
        # a name the register cites as a USE follows the first body that holds it, in START
        # order -- the remaining source first, then the new files -- and is listed once
        stem = "workshop/%s_" % os.path.basename(source).split("_")[0]
        files = [source] + [f for f in end_code_order if f != source and f.startswith(stem)]
        for f in files:
            if f in end_code and has(end_code[f]):
                return [f], "used-in-body" if f != source else "used-in-source"
        return [source], "unresolved"

    out = {}
    regs = subprocess.run(["git", "-C", repo, "ls-tree", "--name-only", commit, "agents/workshop/"],
                          check=True, capture_output=True).stdout.decode().split()
    for reg in sorted(regs):
        if not reg.endswith(".md"):
            continue
        text = git_show(repo, commit, reg)
        paras, lines = split.paragraphs(text)
        new_lines = list(lines)
        for (a, b) in reversed(paras):
            old = lines[a:b]
            joined = " ".join(l.strip() for l in old)
            changed = False
            for source in sources:
                for (s, e, ids) in reversed(split_segments(joined, source, path_re)):
                    groups = collections.OrderedDict()
                    for sp in ids:
                        dests, how = destinations_for(sp, source)
                        decisions.append((reg, source, sp, dests, how))
                        for dst in dests:
                            groups.setdefault(dst, []).append(sp)
                    replacement = "; ".join("`%s` %s" % (dst, ", ".join("`%s`" % x for x in sps))
                                            for dst, sps in groups.items())
                    if replacement != joined[s:e]:
                        joined = joined[:s] + replacement + joined[e:]
                        changed = True
            if changed:
                new_lines[a:b] = split.wrap_from_change(old, joined)
        new_text = "\n".join(new_lines)
        if new_text != text:
            out[reg] = new_text
    how = collections.Counter(d[4] for d in decisions)
    print("registers: %d changed; decisions %s" % (len(out), dict(how)))
    for d in decisions:
        if d[4] != "declared" or d[3] != [d[1]]:
            print("  ", d)
    if report is not None:
        report["__decisions__"] = decisions
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["seed", "apply"])
    ap.add_argument("what", choices=["grab-bags"])
    ap.add_argument("--repo", required=True)
    ap.add_argument("--start", required=True)
    ap.add_argument("--sheet", default=os.path.join(HERE, "sheet.tsv"))
    a = ap.parse_args()
    if a.mode == "seed":
        rows = seed(a.repo, a.start, a.sheet)
        print("seed grab-bags: %d rows -> %s" % (len(rows), a.sheet))
    else:
        apply(a.repo, a.start, a.sheet)


if __name__ == "__main__":
    main()
