// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Joshua DeMoss

#ifndef ZENGINE_BUILDER_GENERATE_HPP
#define ZENGINE_BUILDER_GENERATE_HPP

// Turning an authored recipe into the one process that carries it out -- and, for a
// single-source recipe, writing the tiny CMake project that makes one `.cpp` a loadable
// artifact through the supported package seam, `find_package(zengine CONFIG)`. Zengine drives
// no compiler. The whole build is one generated `cmake -P` driver, so one operation and one
// ending describe it, and a maker authors no line of it.
// Builder law: agents/realization.md

// The toolchain is borrowed, never guessed: the driver `load_cache()`s a configured build tree
// the recipe names (generator, platform, toolset, make program, C++ compiler, build type). An
// MSVC tree needs the Visual Studio environment, inherited from this process and never set
// here. An empty `toolchain_from` lets CMake choose for this machine.
// Reference: docs/reference/builder.md.

#include "builder/recipe.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <system_error>
#include <vector>

namespace zengine::builder {

/// The file the generated project is written to, and the script that drives it. Named
/// once, because the runner starts one and a maker reads the other.
inline constexpr const char* kGeneratedProjectFile = "CMakeLists.txt";
inline constexpr const char* kGeneratedDriverFile = "zengine-build.cmake";
inline constexpr const char* kGeneratedBuildDirName = "build";

/// One authored string as a CMake quoted argument's contents: `"` cannot occur
/// (`check_recipe_path` refuses it), and `\` and `$` are escaped, so `C:\Users\Someone` stays a
/// path rather than a string with a tab in it.
inline std::string cmake_quoted(const std::string& text) {
    std::string out;
    out.reserve(text.size() + 8);
    for (const char c : text) {
        if (c == '\\' || c == '"' || c == '$') {
            out += '\\';
        }
        out += c;
    }
    return out;
}

/// The generated CMake project, as text, so a suite can assert on it on every platform. Each
/// line earns its place: the package floor; `project(... CXX)`; C++20, which the headers need and
/// the package does not impose; `find_package(zengine)`, CONFIG and REQUIRED, the whole purity
/// claim; a SHARED library under `loom_weave_build_contract` (a loadable image's statics die with
/// it, and its absence means the package resolved somewhere unexpected); `<stem>.so`/`.dll` with
/// no `lib`; output directories CMake owns, per-configuration variants included.
inline std::string generated_project(const Recipe& r) {
    const SingleSourceRecipe& one = *r.single_source;
    std::ostringstream out;
    out << "# Generated by Zengine's Builder for recipe `" << r.id << "`. Do not edit:\n"
        << "# it is rewritten from the authored recipe every time this recipe is built.\n"
        << "#\n"
        << "# This is an ORDINARY EXTERNAL CONSUMER of the Zengine package. There is no\n"
        << "# include directory into a Zengine source tree, no path into a Zengine build\n"
        << "# tree, no named .so or .dll and no compile option -- if any of those ever\n"
        << "# became necessary here, the package would have stopped carrying its own\n"
        << "# requirements.\n"
        << "cmake_minimum_required(VERSION 3.16)\n"
        << "project(zengine-recipe-" << r.id << " LANGUAGES CXX)\n"
        << "\n"
        << "set(CMAKE_CXX_STANDARD 20)\n"
        << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        << "\n"
        << "find_package(zengine 0.1 CONFIG REQUIRED)\n"
        << "if(NOT COMMAND loom_weave_build_contract)\n"
        << "    message(FATAL_ERROR\n"
        << "        \"zengine build: the zengine package was found but the Loom's weave build \"\n"
        << "        \"contract is not defined. A loadable image needs it, and its absence \"\n"
        << "        \"means find_package(zengine) resolved somewhere unexpected.\")\n"
        << "endif()\n"
        << "\n"
        << "add_library(" << r.artifact << " SHARED \"" << cmake_quoted(one.source) << "\")\n"
        << "target_link_libraries(" << r.artifact << " PRIVATE\n";
    for (const std::string& link : one.links) {
        out << "    " << link << "\n";
    }
    out << ")\n"
        << "loom_weave_build_contract(" << r.artifact << ")\n"
        << "\n"
        << "# WHERE THE ARTIFACT LANDS IS SET HERE AND NOWHERE ELSE. Nothing stages, copies\n"
        << "# or renames it afterwards, and nothing in Zengine spells its suffix: CMake puts\n"
        << "# the file where this says, under the name this says, with the platform's own\n"
        << "# ending.\n"
        << "set(zengine_artifact_dir \"" << cmake_quoted(r.artifact_dir) << "\")\n"
        << "set_target_properties(" << r.artifact << " PROPERTIES\n"
        << "    PREFIX \"\"\n"
        << "    OUTPUT_NAME \"" << r.artifact << "\"\n"
        << "    LIBRARY_OUTPUT_DIRECTORY \"${zengine_artifact_dir}\"\n"
        << "    RUNTIME_OUTPUT_DIRECTORY \"${zengine_artifact_dir}\"\n"
        << "    ARCHIVE_OUTPUT_DIRECTORY \"${zengine_artifact_dir}\")\n"
        << "foreach(zengine_cfg IN LISTS CMAKE_CONFIGURATION_TYPES)\n"
        << "    string(TOUPPER \"${zengine_cfg}\" zengine_CFG)\n"
        << "    set_target_properties(" << r.artifact << " PROPERTIES\n"
        << "        LIBRARY_OUTPUT_DIRECTORY_${zengine_CFG} \"${zengine_artifact_dir}\"\n"
        << "        RUNTIME_OUTPUT_DIRECTORY_${zengine_CFG} \"${zengine_artifact_dir}\"\n"
        << "        ARCHIVE_OUTPUT_DIRECTORY_${zengine_CFG} \"${zengine_artifact_dir}\")\n"
        << "endforeach()\n";
    return out.str();
}

/// The generated driver, as text: configure, then build, in one process. It tells a failed
/// configure from a failed compile, being the only party that sees both exit codes, and names
/// the generated project in both refusals; nothing is temporary and nothing is deleted.
inline std::string generated_driver(const Recipe& r) {
    const SingleSourceRecipe& one = *r.single_source;
    const std::string src = one.workspace;
    const std::string bin = one.workspace + "/" + kGeneratedBuildDirName;
    std::ostringstream out;
    out << "# Generated by Zengine's Builder for recipe `" << r.id << "`. Do not edit:\n"
        << "# it is rewritten from the authored recipe every time this recipe is built.\n"
        << "#\n"
        << "# Run as `cmake -P " << kGeneratedDriverFile << "`. It configures and builds the\n"
        << "# generated project beside it, in one process, and says which of the two failed.\n"
        << "set(zengine_src \"" << cmake_quoted(src) << "\")\n"
        << "set(zengine_bin \"" << cmake_quoted(bin) << "\")\n"
        // An empty list, not one empty string: `list(APPEND)` onto `""` leads with an empty item.
        << "set(zengine_configure_args)\n";

    if (!one.packages.empty()) {
        // One `-D`, the list separator written `\;` so it survives a script that is CMake too.
        std::string joined;
        for (std::size_t i = 0; i < one.packages.size(); ++i) {
            if (i != 0) {
                joined += "\\;";
            }
            joined += cmake_quoted(one.packages[i]);
        }
        out << "list(APPEND zengine_configure_args \"-DCMAKE_PREFIX_PATH=" << joined << "\")\n";
    }

    out << "\n";
    if (one.toolchain_from.empty()) {
        out << "# NO TOOLCHAIN WAS BORROWED. This recipe names no configured build tree, so\n"
            << "# CMake chooses this machine's default generator and compiler. That is a\n"
            << "# default and is said to be one.\n"
            << "set(zengine_build_type \"\")\n";
    } else {
        out << "# THE TOOLCHAIN IS BORROWED FROM A CONFIGURED BUILD TREE, with CMake's own\n"
            << "# `load_cache`. Nothing here guesses a generator or looks for a compiler.\n"
            << "set(zengine_toolchain \"" << cmake_quoted(one.toolchain_from) << "\")\n"
            << "if(NOT EXISTS \"${zengine_toolchain}/CMakeCache.txt\")\n"
            << "    message(FATAL_ERROR\n"
            << "        \"zengine build: the configured CMake build tree this recipe borrows \"\n"
            << "        \"its toolchain from has no CMakeCache.txt: ${zengine_toolchain}\")\n"
            << "endif()\n"
            // The C compiler is not borrowed: the project is `LANGUAGES CXX`, and an unread
            // `-DCMAKE_C_COMPILER` is a CMake warning in the middle of a maker's build output.
            << "load_cache(\"${zengine_toolchain}\" READ_WITH_PREFIX borrowed_\n"
            << "           CMAKE_GENERATOR CMAKE_GENERATOR_PLATFORM CMAKE_GENERATOR_TOOLSET\n"
            << "           CMAKE_GENERATOR_INSTANCE CMAKE_MAKE_PROGRAM\n"
            << "           CMAKE_CXX_COMPILER CMAKE_BUILD_TYPE)\n"
            << "set(zengine_build_type \"${borrowed_CMAKE_BUILD_TYPE}\")\n"
            << "if(borrowed_CMAKE_GENERATOR)\n"
            << "    list(APPEND zengine_configure_args -G \"${borrowed_CMAKE_GENERATOR}\")\n"
            << "endif()\n"
            << "if(borrowed_CMAKE_GENERATOR_PLATFORM)\n"
            << "    list(APPEND zengine_configure_args -A \"${borrowed_CMAKE_GENERATOR_PLATFORM}\")\n"
            << "endif()\n"
            << "if(borrowed_CMAKE_GENERATOR_TOOLSET)\n"
            << "    list(APPEND zengine_configure_args -T \"${borrowed_CMAKE_GENERATOR_TOOLSET}\")\n"
            << "endif()\n"
            << "foreach(zengine_pair CMAKE_MAKE_PROGRAM CMAKE_CXX_COMPILER)\n"
            << "    if(borrowed_${zengine_pair})\n"
            << "        list(APPEND zengine_configure_args\n"
            << "             \"-D${zengine_pair}=${borrowed_${zengine_pair}}\")\n"
            << "    endif()\n"
            << "endforeach()\n";
    }

    out << "if(zengine_build_type)\n"
        << "    list(APPEND zengine_configure_args \"-DCMAKE_BUILD_TYPE=${zengine_build_type}\")\n"
        << "endif()\n"
        << "\n"
        << "message(STATUS \"zengine build: configuring ${zengine_src}\")\n"
        << "execute_process(\n"
        << "    COMMAND \"${CMAKE_COMMAND}\" -S \"${zengine_src}\" -B \"${zengine_bin}\"\n"
        << "            ${zengine_configure_args}\n"
        << "    RESULT_VARIABLE zengine_rc)\n"
        << "if(NOT zengine_rc EQUAL 0)\n"
        << "    message(FATAL_ERROR\n"
        << "        \"zengine build: CMake configure FAILED (exit ${zengine_rc}). The generated \"\n"
        << "        \"project is at ${zengine_src} and was not deleted.\")\n"
        << "endif()\n"
        << "\n"
        << "message(STATUS \"zengine build: compiling and linking " << r.artifact << "\")\n"
        << "set(zengine_build_args)\n"
        << "if(zengine_build_type)\n"
        << "    list(APPEND zengine_build_args --config \"${zengine_build_type}\")\n"
        << "endif()\n"
        << "execute_process(\n"
        << "    COMMAND \"${CMAKE_COMMAND}\" --build \"${zengine_bin}\" ${zengine_build_args}\n"
        << "    RESULT_VARIABLE zengine_rc)\n"
        << "if(NOT zengine_rc EQUAL 0)\n"
        << "    message(FATAL_ERROR\n"
        << "        \"zengine build: compile or link FAILED (exit ${zengine_rc}). The generated \"\n"
        << "        \"project is at ${zengine_src} and was not deleted.\")\n"
        << "endif()\n"
        << "message(STATUS \"zengine build: " << r.artifact << " built into "
        << cmake_quoted(r.artifact_dir) << "\")\n";
    return out.str();
}

namespace detail {

/// Write only what changed: identical bytes rewritten still move the modification time, and a
/// moved `CMakeLists.txt` would make every press of Build on an unchanged recipe reconfigure.
inline bool write_if_different(const std::filesystem::path& file, const std::string& text,
                               std::string& trouble) {
    std::error_code ec;
    if (std::filesystem::exists(file, ec)) {
        std::ifstream in(file, std::ios::binary);
        if (in) {
            std::ostringstream held;
            held << in.rdbuf();
            if (held.str() == text) {
                return true;
            }
        }
    }
    std::ofstream out(file, std::ios::binary | std::ios::trunc);
    if (!out) {
        trouble = "could not write the generated file " + file.string();
        return false;
    }
    out << text;
    out.close();
    if (!out) {
        trouble = "could not finish writing the generated file " + file.string();
        return false;
    }
    return true;
}

} // namespace detail

/// Put the generated project on disk; empty means it is there. The workspace is created and
/// never removed: the diagnostics must survive for a maker to read, in the directory every
/// refusal names.
inline std::string materialize(const Recipe& r) {
    if (!r.single_source.has_value()) {
        return std::string();
    }
    const std::filesystem::path workspace(r.single_source->workspace);
    std::error_code ec;
    std::filesystem::create_directories(workspace, ec);
    if (ec && !std::filesystem::is_directory(workspace)) {
        return "could not create the build workspace " + workspace.string() + ": " + ec.message();
    }
    std::string trouble;
    if (!detail::write_if_different(workspace / kGeneratedProjectFile, generated_project(r),
                                    trouble)) {
        return trouble;
    }
    if (!detail::write_if_different(workspace / kGeneratedDriverFile, generated_driver(r),
                                    trouble)) {
        return trouble;
    }
    return std::string();
}

/// WHAT ONE RECIPE IS, AS A PROCESS -- and whether it could be made into one at all.
struct PreparedBuild {
    bool ok = false;
    std::string trouble; ///< why not, when not
    BuildCommand command;
};

/// Turn an authored recipe into the one process that carries it out. `cmake` is the host's own
/// CMake by absolute path, never resolved from PATH (another shell's CMake against a tree it did
/// not configure) and never nameable by a recipe. The two preflights are diagnostics, not gates:
/// they name the recipe and the path before CMake would find the same problem.
inline PreparedBuild prepare(const Recipe& r, const std::string& cmake) {
    PreparedBuild out;
    if (cmake.empty()) {
        out.trouble = "this Workshop was built without a CMake to build with";
        return out;
    }
    if (r.cmake_target.has_value()) {
        const CMakeTargetRecipe& t = *r.cmake_target;
        std::error_code ec;
        if (!std::filesystem::exists(std::filesystem::path(t.build_dir) / "CMakeCache.txt", ec)) {
            out.trouble = "the configured CMake build tree `" + t.build_dir +
                          "` has no CMakeCache.txt: recipe `" + r.id +
                          "` builds a target in a tree somebody else configured, and that "
                          "tree is not there";
            return out;
        }
        out.command.program = cmake;
        out.command.args = {"--build", t.build_dir, "--target", t.target};
        if (!t.config.empty()) {
            out.command.args.push_back("--config");
            out.command.args.push_back(t.config);
        }
        out.command.dir = t.build_dir;
        out.ok = true;
        return out;
    }
    if (!r.single_source.has_value()) {
        out.trouble = "recipe `" + r.id + "` names no build mechanism";
        return out;
    }
    const SingleSourceRecipe& one = *r.single_source;
    std::error_code ec;
    if (!std::filesystem::exists(std::filesystem::path(one.source), ec)) {
        out.trouble = "the source file `" + one.source + "` recipe `" + r.id +
                      "` builds is not there";
        return out;
    }
    const std::string wrote = materialize(r);
    if (!wrote.empty()) {
        out.trouble = wrote;
        return out;
    }
    out.command.program = cmake;
    out.command.args = {"-P", one.workspace + "/" + kGeneratedDriverFile};
    out.command.dir = one.workspace;
    out.ok = true;
    return out;
}

} // namespace zengine::builder

#endif // ZENGINE_BUILDER_GENERATE_HPP
