# A FILE'S BYTES AS A C++ TRANSLATION UNIT — run with `cmake -P`, never included.
#
# WHY THIS EXISTS. HD-1 gives the graphical Skin a real typeface, and a real
# typeface is a real file. The three ways a runtime can reach one are: discover it
# on the host (not portable — `consola.ttf` exists on Windows and a headless Linux
# box may have no font at all), stage it beside the binary (a path to resolve, a
# copy rule to forget, and a half-arrived install to diagnose), or carry it. This
# is carrying it. A Skin either has its face or does not; there is no third state
# and nothing to look for at runtime.
#
# It is deliberately generic — a name, an input, an output — because the property
# worth having is that the font is not special. Anything this package ever has to
# carry rather than find goes through the same script.
#
#   cmake -DZEN_EMBED_INPUT=<file> -DZEN_EMBED_OUTPUT=<file.cpp>
#         -DZEN_EMBED_NAME=<identifier> -DZEN_EMBED_NAMESPACE=<ns>
#         -P cmake/EmbedBinary.cmake
#
# The generated unit defines `<ns>::<name>` (an array of unsigned char) and
# `<ns>::<name>_size`. It is written into the BUILD tree: generated code is not
# source, and a 1.6 MB array of decimal bytes checked in beside the 274 KB file it
# was derived from would be a second copy of the same truth.

if(NOT DEFINED ZEN_EMBED_INPUT OR NOT DEFINED ZEN_EMBED_OUTPUT
   OR NOT DEFINED ZEN_EMBED_NAME OR NOT DEFINED ZEN_EMBED_NAMESPACE)
    message(FATAL_ERROR
        "EmbedBinary.cmake: needs ZEN_EMBED_INPUT, ZEN_EMBED_OUTPUT, ZEN_EMBED_NAME "
        "and ZEN_EMBED_NAMESPACE")
endif()

if(NOT EXISTS "${ZEN_EMBED_INPUT}")
    message(FATAL_ERROR "EmbedBinary.cmake: no such file: ${ZEN_EMBED_INPUT}")
endif()

file(READ "${ZEN_EMBED_INPUT}" zen_embed_hex HEX)
string(LENGTH "${zen_embed_hex}" zen_embed_nibbles)
math(EXPR zen_embed_bytes "${zen_embed_nibbles} / 2")
if(zen_embed_bytes EQUAL 0)
    message(FATAL_ERROR "EmbedBinary.cmake: ${ZEN_EMBED_INPUT} is empty")
endif()

# One regex pass over the whole file rather than a loop: CMake's string ops are
# cheap in bulk and ruinous per element, and the 274 KB face is 548 000 nibbles.
# The line break every sixteen bytes is not cosmetic — some compilers slow down
# badly on a single line of a quarter of a million tokens.
string(REGEX REPLACE "(................................)" "\\1\n" zen_embed_rows
       "${zen_embed_hex}")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," zen_embed_body "${zen_embed_rows}")

get_filename_component(zen_embed_origin "${ZEN_EMBED_INPUT}" NAME)

file(WRITE "${ZEN_EMBED_OUTPUT}"
"// GENERATED by cmake/EmbedBinary.cmake from ${zen_embed_origin} -- do not edit, and do
// not check in: the file it came from is the source of truth and lives in the tree.
//
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Joshua DeMoss
//
// The DATA below is not first-party and is not MPL-licensed. It is a byte-for-byte
// copy of ${zen_embed_origin}; that file's licence and provenance travel with it, and
// are recorded beside it and in THIRD_PARTY_NOTICES.md.

#include <cstddef>

namespace ${ZEN_EMBED_NAMESPACE} {

extern const unsigned char ${ZEN_EMBED_NAME}[${zen_embed_bytes}];
extern const std::size_t ${ZEN_EMBED_NAME}_size;

const unsigned char ${ZEN_EMBED_NAME}[${zen_embed_bytes}] = {
${zen_embed_body}
};

const std::size_t ${ZEN_EMBED_NAME}_size = ${zen_embed_bytes};

} // namespace ${ZEN_EMBED_NAMESPACE}
")
